// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module IDST7_IDST7B8_Pipeline_VITIS_LOOP_21_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dst_0,
        dst_0_ap_vld,
        dst_7,
        dst_7_ap_vld,
        dst_6,
        dst_6_ap_vld,
        dst_5,
        dst_5_ap_vld,
        dst_4,
        dst_4_ap_vld,
        dst_3,
        dst_3_ap_vld,
        dst_2,
        dst_2_ap_vld,
        dst_1,
        dst_1_ap_vld,
        src_0_val,
        src_1_val,
        src_2_val,
        src_3_val,
        src_4_val,
        src_5_val,
        src_6_val,
        src_7_val,
        conv3_i12_i_i,
        sh_prom_i9_i_i,
        sh_prom_i_i_i,
        empty_33,
        oMin,
        oMax,
        empty_34,
        cutoff,
        empty_35,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] dst_0;
output   dst_0_ap_vld;
output  [31:0] dst_7;
output   dst_7_ap_vld;
output  [31:0] dst_6;
output   dst_6_ap_vld;
output  [31:0] dst_5;
output   dst_5_ap_vld;
output  [31:0] dst_4;
output   dst_4_ap_vld;
output  [31:0] dst_3;
output   dst_3_ap_vld;
output  [31:0] dst_2;
output   dst_2_ap_vld;
output  [31:0] dst_1;
output   dst_1_ap_vld;
input  [31:0] src_0_val;
input  [31:0] src_1_val;
input  [31:0] src_2_val;
input  [31:0] src_3_val;
input  [31:0] src_4_val;
input  [31:0] src_5_val;
input  [31:0] src_6_val;
input  [31:0] src_7_val;
input  [31:0] conv3_i12_i_i;
input  [31:0] sh_prom_i9_i_i;
input  [31:0] sh_prom_i_i_i;
input  [0:0] empty_33;
input  [31:0] oMin;
input  [31:0] oMax;
input  [28:0] empty_34;
input  [31:0] cutoff;
input  [29:0] empty_35;
input  [30:0] empty;

reg ap_idle;
reg dst_0_ap_vld;
reg dst_7_ap_vld;
reg dst_6_ap_vld;
reg dst_5_ap_vld;
reg dst_4_ap_vld;
reg dst_3_ap_vld;
reg dst_2_ap_vld;
reg dst_1_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln21_fu_512_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] p_ZL7idst7_8_0_address0;
wire   [6:0] p_ZL7idst7_8_0_q0;
wire   [2:0] p_ZL7idst7_8_1_address0;
wire   [7:0] p_ZL7idst7_8_1_q0;
wire   [2:0] p_ZL7idst7_8_2_address0;
wire   [7:0] p_ZL7idst7_8_2_q0;
wire   [2:0] p_ZL7idst7_8_3_address0;
wire   [7:0] p_ZL7idst7_8_3_q0;
wire   [2:0] p_ZL7idst7_8_4_address0;
wire   [7:0] p_ZL7idst7_8_4_q0;
wire   [2:0] p_ZL7idst7_8_5_address0;
wire   [7:0] p_ZL7idst7_8_5_q0;
wire   [2:0] p_ZL7idst7_8_6_address0;
wire   [7:0] p_ZL7idst7_8_6_q0;
wire   [2:0] p_ZL7idst7_8_7_address0;
wire   [7:0] p_ZL7idst7_8_7_q0;
wire    ap_block_pp0_stage0_11001;
wire   [32:0] sh_prom_i_i_i_cast_fu_438_p1;
reg   [32:0] sh_prom_i_i_i_cast_reg_876;
wire   [32:0] sh_prom_i9_i_i_cast_fu_442_p1;
reg   [32:0] sh_prom_i9_i_i_cast_reg_881;
wire  signed [32:0] conv3_i12_i_i_cast_fu_446_p1;
reg  signed [32:0] conv3_i12_i_i_cast_reg_886;
wire   [0:0] icmp50_fu_450_p2;
reg   [0:0] icmp50_reg_891;
wire   [0:0] cmp_i_i_6_fu_456_p2;
reg   [0:0] cmp_i_i_6_reg_896;
wire   [0:0] cmp_i_i_5_fu_462_p2;
reg   [0:0] cmp_i_i_5_reg_901;
wire   [0:0] cmp_i_i_4_fu_468_p2;
reg   [0:0] cmp_i_i_4_reg_906;
wire   [0:0] icmp47_fu_474_p2;
reg   [0:0] icmp47_reg_911;
wire   [0:0] cmp_i_i_2_fu_480_p2;
reg   [0:0] cmp_i_i_2_reg_916;
wire   [0:0] icmp_fu_486_p2;
reg   [0:0] icmp_reg_921;
wire   [0:0] cmp_i_i_fu_492_p2;
reg   [0:0] cmp_i_i_reg_926;
wire   [2:0] trunc_ln21_fu_530_p1;
reg   [2:0] trunc_ln21_reg_935;
reg   [2:0] trunc_ln21_reg_935_pp0_iter1_reg;
reg   [2:0] trunc_ln21_reg_935_pp0_iter2_reg;
reg   [2:0] trunc_ln21_reg_935_pp0_iter3_reg;
reg   [2:0] trunc_ln21_reg_935_pp0_iter4_reg;
reg   [2:0] trunc_ln21_reg_935_pp0_iter5_reg;
reg   [2:0] trunc_ln21_reg_935_pp0_iter6_reg;
reg   [2:0] trunc_ln21_reg_935_pp0_iter7_reg;
reg   [2:0] trunc_ln21_reg_935_pp0_iter8_reg;
wire   [31:0] zext_ln30_fu_571_p1;
wire  signed [31:0] sext_ln30_fu_582_p1;
reg   [7:0] p_ZL7idst7_8_2_load_reg_991;
reg   [7:0] p_ZL7idst7_8_3_load_reg_996;
reg   [7:0] p_ZL7idst7_8_4_load_reg_1001;
reg   [7:0] p_ZL7idst7_8_4_load_reg_1001_pp0_iter2_reg;
reg   [7:0] p_ZL7idst7_8_5_load_reg_1006;
reg   [7:0] p_ZL7idst7_8_5_load_reg_1006_pp0_iter2_reg;
reg   [7:0] p_ZL7idst7_8_5_load_reg_1006_pp0_iter3_reg;
reg   [7:0] p_ZL7idst7_8_6_load_reg_1011;
reg   [7:0] p_ZL7idst7_8_6_load_reg_1011_pp0_iter2_reg;
reg   [7:0] p_ZL7idst7_8_6_load_reg_1011_pp0_iter3_reg;
reg   [7:0] p_ZL7idst7_8_7_load_reg_1016;
reg   [7:0] p_ZL7idst7_8_7_load_reg_1016_pp0_iter2_reg;
reg   [7:0] p_ZL7idst7_8_7_load_reg_1016_pp0_iter3_reg;
reg   [7:0] p_ZL7idst7_8_7_load_reg_1016_pp0_iter4_reg;
wire  signed [31:0] sext_ln30_1_fu_593_p1;
wire  signed [31:0] sext_ln30_2_fu_603_p1;
wire   [31:0] sum_3_fu_626_p3;
reg   [31:0] sum_3_reg_1033;
wire  signed [31:0] sext_ln30_3_fu_633_p1;
wire   [31:0] sum_5_fu_648_p3;
reg   [31:0] sum_5_reg_1045;
wire   [31:0] sum_6_fu_654_p2;
reg   [31:0] sum_6_reg_1050;
wire  signed [31:0] sext_ln30_4_fu_660_p1;
wire  signed [31:0] sext_ln30_5_fu_670_p1;
wire   [31:0] sum_9_fu_691_p3;
reg   [31:0] sum_9_reg_1067;
wire  signed [31:0] sext_ln30_6_fu_698_p1;
wire   [31:0] sum_11_fu_713_p3;
reg   [31:0] sum_11_reg_1079;
wire   [31:0] sum_12_fu_719_p2;
reg   [31:0] sum_12_reg_1084;
wire   [32:0] add_ln34_fu_747_p2;
reg   [32:0] add_ln34_reg_1089;
wire   [31:0] scaled_fu_768_p3;
reg   [31:0] scaled_reg_1095;
wire   [63:0] zext_ln21_fu_518_p1;
wire    ap_block_pp0_stage0;
reg   [3:0] j_fu_134;
wire   [3:0] add_ln21_fu_506_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_1;
wire   [31:0] select_ln8_fu_789_p3;
wire    ap_block_pp0_stage0_01001;
reg    p_ZL7idst7_8_0_ce0_local;
reg    p_ZL7idst7_8_1_ce0_local;
reg    p_ZL7idst7_8_2_ce0_local;
reg    p_ZL7idst7_8_3_ce0_local;
reg    p_ZL7idst7_8_4_ce0_local;
reg    p_ZL7idst7_8_5_ce0_local;
reg    p_ZL7idst7_8_6_ce0_local;
reg    p_ZL7idst7_8_7_ce0_local;
reg   [6:0] grp_fu_406_p0;
reg  signed [31:0] grp_fu_406_p1;
reg  signed [7:0] grp_fu_410_p0;
reg  signed [31:0] grp_fu_410_p1;
reg  signed [7:0] grp_fu_414_p0;
reg  signed [31:0] grp_fu_414_p1;
reg  signed [7:0] grp_fu_418_p0;
reg  signed [31:0] grp_fu_418_p1;
reg  signed [7:0] grp_fu_422_p0;
reg  signed [31:0] grp_fu_422_p1;
reg  signed [7:0] grp_fu_426_p0;
reg  signed [31:0] grp_fu_426_p1;
reg  signed [7:0] grp_fu_430_p0;
reg  signed [31:0] grp_fu_430_p1;
reg  signed [7:0] grp_fu_434_p0;
reg  signed [31:0] grp_fu_434_p1;
reg   [31:0] grp_fu_406_p2;
reg   [31:0] grp_fu_410_p2;
wire   [31:0] sum_1_fu_613_p3;
wire   [31:0] sum_2_fu_620_p2;
reg   [31:0] grp_fu_414_p2;
wire   [31:0] sum_4_fu_643_p2;
reg   [31:0] grp_fu_418_p2;
reg   [31:0] grp_fu_422_p2;
wire   [31:0] sum_7_fu_680_p3;
wire   [31:0] sum_8_fu_685_p2;
reg   [31:0] grp_fu_426_p2;
wire   [31:0] sum_10_fu_708_p2;
reg   [31:0] grp_fu_430_p2;
reg   [31:0] grp_fu_434_p2;
wire   [31:0] sum_13_fu_725_p3;
wire   [31:0] sum_14_fu_730_p2;
wire   [31:0] sum_15_fu_736_p3;
wire  signed [32:0] sext_ln34_fu_743_p1;
wire   [32:0] shl_ln34_fu_752_p2;
wire   [32:0] ashr_ln34_fu_756_p2;
wire   [31:0] trunc_ln34_fu_760_p1;
wire   [31:0] trunc_ln34_1_fu_764_p1;
wire   [0:0] icmp_ln9_fu_779_p2;
wire   [0:0] icmp_ln8_fu_775_p2;
wire   [31:0] select_ln9_fu_783_p3;
reg    grp_fu_406_ce;
wire   [31:0] pre_grp_fu_406_p2;
reg   [31:0] pre_grp_fu_406_p2_reg;
reg    grp_fu_410_ce;
wire   [31:0] pre_grp_fu_410_p2;
reg   [31:0] pre_grp_fu_410_p2_reg;
reg    grp_fu_414_ce;
wire   [31:0] pre_grp_fu_414_p2;
reg   [31:0] pre_grp_fu_414_p2_reg;
reg    grp_fu_418_ce;
wire   [31:0] pre_grp_fu_418_p2;
reg   [31:0] pre_grp_fu_418_p2_reg;
reg    grp_fu_422_ce;
wire   [31:0] pre_grp_fu_422_p2;
reg   [31:0] pre_grp_fu_422_p2_reg;
reg    grp_fu_426_ce;
wire   [31:0] pre_grp_fu_426_p2;
reg   [31:0] pre_grp_fu_426_p2_reg;
reg    grp_fu_430_ce;
wire   [31:0] pre_grp_fu_430_p2;
reg   [31:0] pre_grp_fu_430_p2_reg;
reg    grp_fu_434_ce;
wire   [31:0] pre_grp_fu_434_p2;
reg   [31:0] pre_grp_fu_434_p2_reg;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 j_fu_134 = 4'd0;
#0 ap_done_reg = 1'b0;
end

IDST7_IDST7B8_Pipeline_VITIS_LOOP_21_1_p_ZL7idst7_8_0_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7idst7_8_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7idst7_8_0_address0),
    .ce0(p_ZL7idst7_8_0_ce0_local),
    .q0(p_ZL7idst7_8_0_q0)
);

IDST7_IDST7B8_Pipeline_VITIS_LOOP_21_1_p_ZL7idst7_8_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7idst7_8_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7idst7_8_1_address0),
    .ce0(p_ZL7idst7_8_1_ce0_local),
    .q0(p_ZL7idst7_8_1_q0)
);

IDST7_IDST7B8_Pipeline_VITIS_LOOP_21_1_p_ZL7idst7_8_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7idst7_8_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7idst7_8_2_address0),
    .ce0(p_ZL7idst7_8_2_ce0_local),
    .q0(p_ZL7idst7_8_2_q0)
);

IDST7_IDST7B8_Pipeline_VITIS_LOOP_21_1_p_ZL7idst7_8_3_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7idst7_8_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7idst7_8_3_address0),
    .ce0(p_ZL7idst7_8_3_ce0_local),
    .q0(p_ZL7idst7_8_3_q0)
);

IDST7_IDST7B8_Pipeline_VITIS_LOOP_21_1_p_ZL7idst7_8_4_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7idst7_8_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7idst7_8_4_address0),
    .ce0(p_ZL7idst7_8_4_ce0_local),
    .q0(p_ZL7idst7_8_4_q0)
);

IDST7_IDST7B8_Pipeline_VITIS_LOOP_21_1_p_ZL7idst7_8_5_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7idst7_8_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7idst7_8_5_address0),
    .ce0(p_ZL7idst7_8_5_ce0_local),
    .q0(p_ZL7idst7_8_5_q0)
);

IDST7_IDST7B8_Pipeline_VITIS_LOOP_21_1_p_ZL7idst7_8_6_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7idst7_8_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7idst7_8_6_address0),
    .ce0(p_ZL7idst7_8_6_ce0_local),
    .q0(p_ZL7idst7_8_6_q0)
);

IDST7_IDST7B8_Pipeline_VITIS_LOOP_21_1_p_ZL7idst7_8_7_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
p_ZL7idst7_8_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL7idst7_8_7_address0),
    .ce0(p_ZL7idst7_8_7_ce0_local),
    .q0(p_ZL7idst7_8_7_q0)
);

IDST7_mul_7ns_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_7ns_32s_32_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_406_p0),
    .din1(grp_fu_406_p1),
    .ce(grp_fu_406_ce),
    .dout(pre_grp_fu_406_p2)
);

IDST7_mul_8s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_410_p0),
    .din1(grp_fu_410_p1),
    .ce(grp_fu_410_ce),
    .dout(pre_grp_fu_410_p2)
);

IDST7_mul_8s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_414_p0),
    .din1(grp_fu_414_p1),
    .ce(grp_fu_414_ce),
    .dout(pre_grp_fu_414_p2)
);

IDST7_mul_8s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_418_p0),
    .din1(grp_fu_418_p1),
    .ce(grp_fu_418_ce),
    .dout(pre_grp_fu_418_p2)
);

IDST7_mul_8s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_422_p0),
    .din1(grp_fu_422_p1),
    .ce(grp_fu_422_ce),
    .dout(pre_grp_fu_422_p2)
);

IDST7_mul_8s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_426_p0),
    .din1(grp_fu_426_p1),
    .ce(grp_fu_426_ce),
    .dout(pre_grp_fu_426_p2)
);

IDST7_mul_8s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_430_p0),
    .din1(grp_fu_430_p1),
    .ce(grp_fu_430_ce),
    .dout(pre_grp_fu_430_p2)
);

IDST7_mul_8s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_434_p0),
    .din1(grp_fu_434_p1),
    .ce(grp_fu_434_ce),
    .dout(pre_grp_fu_434_p2)
);

IDST7_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_406_ce <= 1'b1;
    end else begin
        grp_fu_406_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_410_ce <= 1'b1;
    end else begin
        grp_fu_410_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_414_ce <= 1'b1;
    end else begin
        grp_fu_414_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_418_ce <= 1'b1;
    end else begin
        grp_fu_418_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_422_ce <= 1'b1;
    end else begin
        grp_fu_422_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_426_ce <= 1'b1;
    end else begin
        grp_fu_426_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_430_ce <= 1'b1;
    end else begin
        grp_fu_430_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_434_ce <= 1'b1;
    end else begin
        grp_fu_434_ce <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln21_fu_512_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_134 <= add_ln21_fu_506_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_134 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln34_reg_1089 <= add_ln34_fu_747_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        p_ZL7idst7_8_4_load_reg_1001_pp0_iter2_reg <= p_ZL7idst7_8_4_load_reg_1001;
        p_ZL7idst7_8_5_load_reg_1006_pp0_iter2_reg <= p_ZL7idst7_8_5_load_reg_1006;
        p_ZL7idst7_8_5_load_reg_1006_pp0_iter3_reg <= p_ZL7idst7_8_5_load_reg_1006_pp0_iter2_reg;
        p_ZL7idst7_8_6_load_reg_1011_pp0_iter2_reg <= p_ZL7idst7_8_6_load_reg_1011;
        p_ZL7idst7_8_6_load_reg_1011_pp0_iter3_reg <= p_ZL7idst7_8_6_load_reg_1011_pp0_iter2_reg;
        p_ZL7idst7_8_7_load_reg_1016_pp0_iter2_reg <= p_ZL7idst7_8_7_load_reg_1016;
        p_ZL7idst7_8_7_load_reg_1016_pp0_iter3_reg <= p_ZL7idst7_8_7_load_reg_1016_pp0_iter2_reg;
        p_ZL7idst7_8_7_load_reg_1016_pp0_iter4_reg <= p_ZL7idst7_8_7_load_reg_1016_pp0_iter3_reg;
        scaled_reg_1095 <= scaled_fu_768_p3;
        sum_11_reg_1079 <= sum_11_fu_713_p3;
        sum_12_reg_1084 <= sum_12_fu_719_p2;
        sum_3_reg_1033 <= sum_3_fu_626_p3;
        sum_5_reg_1045 <= sum_5_fu_648_p3;
        sum_6_reg_1050 <= sum_6_fu_654_p2;
        sum_9_reg_1067 <= sum_9_fu_691_p3;
        trunc_ln21_reg_935_pp0_iter2_reg <= trunc_ln21_reg_935_pp0_iter1_reg;
        trunc_ln21_reg_935_pp0_iter3_reg <= trunc_ln21_reg_935_pp0_iter2_reg;
        trunc_ln21_reg_935_pp0_iter4_reg <= trunc_ln21_reg_935_pp0_iter3_reg;
        trunc_ln21_reg_935_pp0_iter5_reg <= trunc_ln21_reg_935_pp0_iter4_reg;
        trunc_ln21_reg_935_pp0_iter6_reg <= trunc_ln21_reg_935_pp0_iter5_reg;
        trunc_ln21_reg_935_pp0_iter7_reg <= trunc_ln21_reg_935_pp0_iter6_reg;
        trunc_ln21_reg_935_pp0_iter8_reg <= trunc_ln21_reg_935_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp_i_i_2_reg_916 <= cmp_i_i_2_fu_480_p2;
        cmp_i_i_4_reg_906 <= cmp_i_i_4_fu_468_p2;
        cmp_i_i_5_reg_901 <= cmp_i_i_5_fu_462_p2;
        cmp_i_i_6_reg_896 <= cmp_i_i_6_fu_456_p2;
        cmp_i_i_reg_926 <= cmp_i_i_fu_492_p2;
        conv3_i12_i_i_cast_reg_886 <= conv3_i12_i_i_cast_fu_446_p1;
        icmp47_reg_911 <= icmp47_fu_474_p2;
        icmp50_reg_891 <= icmp50_fu_450_p2;
        icmp_reg_921 <= icmp_fu_486_p2;
        p_ZL7idst7_8_2_load_reg_991 <= p_ZL7idst7_8_2_q0;
        p_ZL7idst7_8_3_load_reg_996 <= p_ZL7idst7_8_3_q0;
        p_ZL7idst7_8_4_load_reg_1001 <= p_ZL7idst7_8_4_q0;
        p_ZL7idst7_8_5_load_reg_1006 <= p_ZL7idst7_8_5_q0;
        p_ZL7idst7_8_6_load_reg_1011 <= p_ZL7idst7_8_6_q0;
        p_ZL7idst7_8_7_load_reg_1016 <= p_ZL7idst7_8_7_q0;
        sh_prom_i9_i_i_cast_reg_881[31 : 0] <= sh_prom_i9_i_i_cast_fu_442_p1[31 : 0];
        sh_prom_i_i_i_cast_reg_876[31 : 0] <= sh_prom_i_i_i_cast_fu_438_p1[31 : 0];
        trunc_ln21_reg_935 <= trunc_ln21_fu_530_p1;
        trunc_ln21_reg_935_pp0_iter1_reg <= trunc_ln21_reg_935;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_406_p0 <= zext_ln30_fu_571_p1;
        grp_fu_406_p1 <= src_0_val;
        grp_fu_410_p0 <= sext_ln30_fu_582_p1;
        grp_fu_410_p1 <= src_1_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        grp_fu_414_p0 <= sext_ln30_1_fu_593_p1;
        grp_fu_414_p1 <= src_2_val;
        grp_fu_418_p0 <= sext_ln30_2_fu_603_p1;
        grp_fu_418_p1 <= src_3_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        grp_fu_422_p0 <= sext_ln30_3_fu_633_p1;
        grp_fu_422_p1 <= src_4_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        grp_fu_426_p0 <= sext_ln30_4_fu_660_p1;
        grp_fu_426_p1 <= src_5_val;
        grp_fu_430_p0 <= sext_ln30_5_fu_670_p1;
        grp_fu_430_p1 <= src_6_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        grp_fu_434_p0 <= sext_ln30_6_fu_698_p1;
        grp_fu_434_p1 <= src_7_val;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_406_ce == 1'b1)) begin
        pre_grp_fu_406_p2_reg <= pre_grp_fu_406_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_410_ce == 1'b1)) begin
        pre_grp_fu_410_p2_reg <= pre_grp_fu_410_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_414_ce == 1'b1)) begin
        pre_grp_fu_414_p2_reg <= pre_grp_fu_414_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_418_ce == 1'b1)) begin
        pre_grp_fu_418_p2_reg <= pre_grp_fu_418_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_422_ce == 1'b1)) begin
        pre_grp_fu_422_p2_reg <= pre_grp_fu_422_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_426_ce == 1'b1)) begin
        pre_grp_fu_426_p2_reg <= pre_grp_fu_426_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_430_ce == 1'b1)) begin
        pre_grp_fu_430_p2_reg <= pre_grp_fu_430_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_434_ce == 1'b1)) begin
        pre_grp_fu_434_p2_reg <= pre_grp_fu_434_p2;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_512_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln21_reg_935_pp0_iter8_reg == 3'd0))) begin
        dst_0_ap_vld = 1'b1;
    end else begin
        dst_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln21_reg_935_pp0_iter8_reg == 3'd1))) begin
        dst_1_ap_vld = 1'b1;
    end else begin
        dst_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln21_reg_935_pp0_iter8_reg == 3'd2))) begin
        dst_2_ap_vld = 1'b1;
    end else begin
        dst_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln21_reg_935_pp0_iter8_reg == 3'd3))) begin
        dst_3_ap_vld = 1'b1;
    end else begin
        dst_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln21_reg_935_pp0_iter8_reg == 3'd4))) begin
        dst_4_ap_vld = 1'b1;
    end else begin
        dst_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln21_reg_935_pp0_iter8_reg == 3'd5))) begin
        dst_5_ap_vld = 1'b1;
    end else begin
        dst_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln21_reg_935_pp0_iter8_reg == 3'd6))) begin
        dst_6_ap_vld = 1'b1;
    end else begin
        dst_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (trunc_ln21_reg_935_pp0_iter8_reg == 3'd7))) begin
        dst_7_ap_vld = 1'b1;
    end else begin
        dst_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fu_406_ce == 1'b1)) begin
        grp_fu_406_p2 = pre_grp_fu_406_p2;
    end else begin
        grp_fu_406_p2 = pre_grp_fu_406_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_410_ce == 1'b1)) begin
        grp_fu_410_p2 = pre_grp_fu_410_p2;
    end else begin
        grp_fu_410_p2 = pre_grp_fu_410_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_414_ce == 1'b1)) begin
        grp_fu_414_p2 = pre_grp_fu_414_p2;
    end else begin
        grp_fu_414_p2 = pre_grp_fu_414_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_418_ce == 1'b1)) begin
        grp_fu_418_p2 = pre_grp_fu_418_p2;
    end else begin
        grp_fu_418_p2 = pre_grp_fu_418_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_422_ce == 1'b1)) begin
        grp_fu_422_p2 = pre_grp_fu_422_p2;
    end else begin
        grp_fu_422_p2 = pre_grp_fu_422_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_426_ce == 1'b1)) begin
        grp_fu_426_p2 = pre_grp_fu_426_p2;
    end else begin
        grp_fu_426_p2 = pre_grp_fu_426_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_430_ce == 1'b1)) begin
        grp_fu_430_p2 = pre_grp_fu_430_p2;
    end else begin
        grp_fu_430_p2 = pre_grp_fu_430_p2_reg;
    end
end

always @ (*) begin
    if ((grp_fu_434_ce == 1'b1)) begin
        grp_fu_434_p2 = pre_grp_fu_434_p2;
    end else begin
        grp_fu_434_p2 = pre_grp_fu_434_p2_reg;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_512_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i_fu_492_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL7idst7_8_0_ce0_local = 1'b1;
    end else begin
        p_ZL7idst7_8_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_512_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_fu_486_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL7idst7_8_1_ce0_local = 1'b1;
    end else begin
        p_ZL7idst7_8_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_512_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i_2_fu_480_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL7idst7_8_2_ce0_local = 1'b1;
    end else begin
        p_ZL7idst7_8_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_512_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp47_fu_474_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL7idst7_8_3_ce0_local = 1'b1;
    end else begin
        p_ZL7idst7_8_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_512_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i_4_fu_468_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL7idst7_8_4_ce0_local = 1'b1;
    end else begin
        p_ZL7idst7_8_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_512_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i_5_fu_462_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL7idst7_8_5_ce0_local = 1'b1;
    end else begin
        p_ZL7idst7_8_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_512_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (cmp_i_i_6_fu_456_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL7idst7_8_6_ce0_local = 1'b1;
    end else begin
        p_ZL7idst7_8_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_512_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp50_fu_450_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL7idst7_8_7_ce0_local = 1'b1;
    end else begin
        p_ZL7idst7_8_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_506_p2 = (ap_sig_allocacmp_j_1 + 4'd1);

assign add_ln34_fu_747_p2 = ($signed(sext_ln34_fu_743_p1) + $signed(conv3_i12_i_i_cast_reg_886));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign ashr_ln34_fu_756_p2 = $signed(add_ln34_reg_1089) >>> sh_prom_i_i_i_cast_reg_876;

assign cmp_i_i_2_fu_480_p2 = (($signed(cutoff) > $signed(32'd2)) ? 1'b1 : 1'b0);

assign cmp_i_i_4_fu_468_p2 = (($signed(cutoff) > $signed(32'd4)) ? 1'b1 : 1'b0);

assign cmp_i_i_5_fu_462_p2 = (($signed(cutoff) > $signed(32'd5)) ? 1'b1 : 1'b0);

assign cmp_i_i_6_fu_456_p2 = (($signed(cutoff) > $signed(32'd6)) ? 1'b1 : 1'b0);

assign cmp_i_i_fu_492_p2 = (($signed(cutoff) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign conv3_i12_i_i_cast_fu_446_p1 = $signed(conv3_i12_i_i);

assign dst_0 = select_ln8_fu_789_p3;

assign dst_1 = select_ln8_fu_789_p3;

assign dst_2 = select_ln8_fu_789_p3;

assign dst_3 = select_ln8_fu_789_p3;

assign dst_4 = select_ln8_fu_789_p3;

assign dst_5 = select_ln8_fu_789_p3;

assign dst_6 = select_ln8_fu_789_p3;

assign dst_7 = select_ln8_fu_789_p3;

assign icmp47_fu_474_p2 = (($signed(empty_35) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp50_fu_450_p2 = (($signed(empty_34) > $signed(29'd0)) ? 1'b1 : 1'b0);

assign icmp_fu_486_p2 = (($signed(empty) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_512_p2 = ((ap_sig_allocacmp_j_1 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_775_p2 = (($signed(scaled_reg_1095) < $signed(oMin)) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_779_p2 = (($signed(scaled_reg_1095) > $signed(oMax)) ? 1'b1 : 1'b0);

assign p_ZL7idst7_8_0_address0 = zext_ln21_fu_518_p1;

assign p_ZL7idst7_8_1_address0 = zext_ln21_fu_518_p1;

assign p_ZL7idst7_8_2_address0 = zext_ln21_fu_518_p1;

assign p_ZL7idst7_8_3_address0 = zext_ln21_fu_518_p1;

assign p_ZL7idst7_8_4_address0 = zext_ln21_fu_518_p1;

assign p_ZL7idst7_8_5_address0 = zext_ln21_fu_518_p1;

assign p_ZL7idst7_8_6_address0 = zext_ln21_fu_518_p1;

assign p_ZL7idst7_8_7_address0 = zext_ln21_fu_518_p1;

assign scaled_fu_768_p3 = ((empty_33[0:0] == 1'b1) ? trunc_ln34_fu_760_p1 : trunc_ln34_1_fu_764_p1);

assign select_ln8_fu_789_p3 = ((icmp_ln8_fu_775_p2[0:0] == 1'b1) ? oMin : select_ln9_fu_783_p3);

assign select_ln9_fu_783_p3 = ((icmp_ln9_fu_779_p2[0:0] == 1'b1) ? oMax : scaled_reg_1095);

assign sext_ln30_1_fu_593_p1 = $signed(p_ZL7idst7_8_2_load_reg_991);

assign sext_ln30_2_fu_603_p1 = $signed(p_ZL7idst7_8_3_load_reg_996);

assign sext_ln30_3_fu_633_p1 = $signed(p_ZL7idst7_8_4_load_reg_1001_pp0_iter2_reg);

assign sext_ln30_4_fu_660_p1 = $signed(p_ZL7idst7_8_5_load_reg_1006_pp0_iter3_reg);

assign sext_ln30_5_fu_670_p1 = $signed(p_ZL7idst7_8_6_load_reg_1011_pp0_iter3_reg);

assign sext_ln30_6_fu_698_p1 = $signed(p_ZL7idst7_8_7_load_reg_1016_pp0_iter4_reg);

assign sext_ln30_fu_582_p1 = $signed(p_ZL7idst7_8_1_q0);

assign sext_ln34_fu_743_p1 = $signed(sum_15_fu_736_p3);

assign sh_prom_i9_i_i_cast_fu_442_p1 = sh_prom_i9_i_i;

assign sh_prom_i_i_i_cast_fu_438_p1 = sh_prom_i_i_i;

assign shl_ln34_fu_752_p2 = add_ln34_reg_1089 << sh_prom_i9_i_i_cast_reg_881;

assign sum_10_fu_708_p2 = (grp_fu_426_p2 + sum_9_reg_1067);

assign sum_11_fu_713_p3 = ((cmp_i_i_5_reg_901[0:0] == 1'b1) ? sum_10_fu_708_p2 : sum_9_reg_1067);

assign sum_12_fu_719_p2 = (grp_fu_430_p2 + sum_11_fu_713_p3);

assign sum_13_fu_725_p3 = ((cmp_i_i_6_reg_896[0:0] == 1'b1) ? sum_12_reg_1084 : sum_11_reg_1079);

assign sum_14_fu_730_p2 = (grp_fu_434_p2 + sum_13_fu_725_p3);

assign sum_15_fu_736_p3 = ((icmp50_reg_891[0:0] == 1'b1) ? sum_14_fu_730_p2 : sum_13_fu_725_p3);

assign sum_1_fu_613_p3 = ((cmp_i_i_reg_926[0:0] == 1'b1) ? grp_fu_406_p2 : 32'd0);

assign sum_2_fu_620_p2 = (grp_fu_410_p2 + sum_1_fu_613_p3);

assign sum_3_fu_626_p3 = ((icmp_reg_921[0:0] == 1'b1) ? sum_2_fu_620_p2 : sum_1_fu_613_p3);

assign sum_4_fu_643_p2 = (grp_fu_414_p2 + sum_3_reg_1033);

assign sum_5_fu_648_p3 = ((cmp_i_i_2_reg_916[0:0] == 1'b1) ? sum_4_fu_643_p2 : sum_3_reg_1033);

assign sum_6_fu_654_p2 = (grp_fu_418_p2 + sum_5_fu_648_p3);

assign sum_7_fu_680_p3 = ((icmp47_reg_911[0:0] == 1'b1) ? sum_6_reg_1050 : sum_5_reg_1045);

assign sum_8_fu_685_p2 = (grp_fu_422_p2 + sum_7_fu_680_p3);

assign sum_9_fu_691_p3 = ((cmp_i_i_4_reg_906[0:0] == 1'b1) ? sum_8_fu_685_p2 : sum_7_fu_680_p3);

assign trunc_ln21_fu_530_p1 = ap_sig_allocacmp_j_1[2:0];

assign trunc_ln34_1_fu_764_p1 = ashr_ln34_fu_756_p2[31:0];

assign trunc_ln34_fu_760_p1 = shl_ln34_fu_752_p2[31:0];

assign zext_ln21_fu_518_p1 = ap_sig_allocacmp_j_1;

assign zext_ln30_fu_571_p1 = p_ZL7idst7_8_0_q0;

always @ (posedge ap_clk) begin
    sh_prom_i_i_i_cast_reg_876[32] <= 1'b0;
    sh_prom_i9_i_i_cast_reg_881[32] <= 1'b0;
end

endmodule //IDST7_IDST7B8_Pipeline_VITIS_LOOP_21_1
