-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity IDCT2_IDCT2B4 is
port (
    ap_ready : OUT STD_LOGIC;
    in_0_val : IN STD_LOGIC_VECTOR (25 downto 0);
    in_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_2_val : IN STD_LOGIC_VECTOR (25 downto 0);
    in_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of IDCT2_IDCT2B4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_FFFFFFAD : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111110101101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal call_ret_IDCT2B2_fu_50_ap_ready : STD_LOGIC;
    signal call_ret_IDCT2B2_fu_50_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B2_fu_50_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln41_fu_58_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln40_fu_72_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln40_1_fu_78_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln40_1_fu_84_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln40_2_fu_90_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln40_2_fu_96_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln40_3_fu_108_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln40_4_fu_114_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln40_3_fu_108_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln40_4_fu_114_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln40_3_fu_120_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln40_fu_102_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln41_fu_132_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln41_fu_58_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln41_1_fu_138_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln40_fu_126_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln41_fu_144_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln43_fu_150_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_fu_156_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln45_fu_162_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln46_fu_168_p2 : STD_LOGIC_VECTOR (31 downto 0);

    component IDCT2_IDCT2B2 IS
    port (
        ap_ready : OUT STD_LOGIC;
        in_0_val : IN STD_LOGIC_VECTOR (25 downto 0);
        in_1_val : IN STD_LOGIC_VECTOR (25 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;


    component IDCT2_mul_32s_8s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    call_ret_IDCT2B2_fu_50 : component IDCT2_IDCT2B2
    port map (
        ap_ready => call_ret_IDCT2B2_fu_50_ap_ready,
        in_0_val => in_0_val,
        in_1_val => in_2_val,
        ap_return_0 => call_ret_IDCT2B2_fu_50_ap_return_0,
        ap_return_1 => call_ret_IDCT2B2_fu_50_ap_return_1,
        ap_rst => ap_rst);

    mul_32s_8s_32_1_1_U3 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_3_val,
        din1 => mul_ln41_fu_58_p1,
        dout => mul_ln41_fu_58_p2);




    add_ln40_1_fu_84_p2 <= std_logic_vector(unsigned(shl_ln40_fu_72_p2) + unsigned(shl_ln40_1_fu_78_p2));
    add_ln40_2_fu_96_p2 <= std_logic_vector(unsigned(add_ln40_1_fu_84_p2) + unsigned(shl_ln40_2_fu_90_p2));
    add_ln40_3_fu_120_p2 <= std_logic_vector(unsigned(shl_ln40_3_fu_108_p2) + unsigned(shl_ln40_4_fu_114_p2));
    add_ln40_fu_126_p2 <= std_logic_vector(unsigned(add_ln40_3_fu_120_p2) + unsigned(sub_ln40_fu_102_p2));
    add_ln41_1_fu_138_p2 <= std_logic_vector(unsigned(shl_ln41_fu_132_p2) + unsigned(shl_ln40_2_fu_90_p2));
    add_ln41_fu_144_p2 <= std_logic_vector(unsigned(mul_ln41_fu_58_p2) + unsigned(add_ln41_1_fu_138_p2));
    add_ln43_fu_150_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B2_fu_50_ap_return_0) + unsigned(add_ln40_fu_126_p2));
    add_ln44_fu_156_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B2_fu_50_ap_return_1) + unsigned(add_ln41_fu_144_p2));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln43_fu_150_p2;
    ap_return_1 <= add_ln44_fu_156_p2;
    ap_return_2 <= sub_ln45_fu_162_p2;
    ap_return_3 <= sub_ln46_fu_168_p2;
    mul_ln41_fu_58_p1 <= ap_const_lv32_FFFFFFAD(8 - 1 downto 0);
    shl_ln40_1_fu_78_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln40_2_fu_90_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln40_3_fu_108_p0 <= in_3_val;
    shl_ln40_3_fu_108_p2 <= std_logic_vector(shift_left(unsigned(shl_ln40_3_fu_108_p0),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln40_4_fu_114_p0 <= in_3_val;
    shl_ln40_4_fu_114_p2 <= std_logic_vector(shift_left(unsigned(shl_ln40_4_fu_114_p0),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln40_fu_72_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln41_fu_132_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    sub_ln40_fu_102_p2 <= std_logic_vector(unsigned(add_ln40_2_fu_96_p2) - unsigned(in_1_val));
    sub_ln45_fu_162_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B2_fu_50_ap_return_1) - unsigned(add_ln41_fu_144_p2));
    sub_ln46_fu_168_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B2_fu_50_ap_return_0) - unsigned(add_ln40_fu_126_p2));
end behav;
