-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity IDCT8_IDCT8B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idct8_32_31_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of IDCT8_IDCT8B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idct8_32_31_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000100", 1 => "11110011", 2 => "00010101", 3 => "11100010", 
    4 => "00100110", 5 => "11010010", 6 => "00110101", 7 => "11000100", 
    8 => "01000010", 9 => "10111000", 10 => "01001101", 11 => "10110000", 
    12 => "01010100", 13 => "10101010", 14 => "01011000", 15 => "10100110", 
    16 => "01011010", 17 => "10100111", 18 => "01010111", 19 => "10101011", 
    20 => "01010010", 21 => "10110010", 22 => "01001010", 23 => "10111100", 
    24 => "00111111", 25 => "11001000", 26 => "00110010", 27 => "11010110", 
    28 => "00100010", 29 => "11100110", 30 => "00010001", 31 => "11110111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

