// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dst_0,
        dst_0_ap_vld,
        dst_15,
        dst_15_ap_vld,
        dst_14,
        dst_14_ap_vld,
        dst_13,
        dst_13_ap_vld,
        dst_12,
        dst_12_ap_vld,
        dst_11,
        dst_11_ap_vld,
        dst_10,
        dst_10_ap_vld,
        dst_9,
        dst_9_ap_vld,
        dst_8,
        dst_8_ap_vld,
        dst_7,
        dst_7_ap_vld,
        dst_6,
        dst_6_ap_vld,
        dst_5,
        dst_5_ap_vld,
        dst_4,
        dst_4_ap_vld,
        dst_3,
        dst_3_ap_vld,
        dst_2,
        dst_2_ap_vld,
        dst_1,
        dst_1_ap_vld,
        src_0_val,
        src_1_val,
        src_2_val,
        src_3_val,
        src_4_val,
        src_5_val,
        src_6_val,
        src_7_val,
        src_8_val,
        src_9_val,
        src_10_val,
        src_11_val,
        src_12_val,
        src_13_val,
        src_14_val,
        src_15_val,
        conv3_i12_i_i,
        sh_prom_i9_i_i,
        sh_prom_i_i_i,
        empty_44,
        oMin,
        oMax,
        empty_45,
        cutoff,
        empty_46,
        empty_47,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] dst_0;
output   dst_0_ap_vld;
output  [31:0] dst_15;
output   dst_15_ap_vld;
output  [31:0] dst_14;
output   dst_14_ap_vld;
output  [31:0] dst_13;
output   dst_13_ap_vld;
output  [31:0] dst_12;
output   dst_12_ap_vld;
output  [31:0] dst_11;
output   dst_11_ap_vld;
output  [31:0] dst_10;
output   dst_10_ap_vld;
output  [31:0] dst_9;
output   dst_9_ap_vld;
output  [31:0] dst_8;
output   dst_8_ap_vld;
output  [31:0] dst_7;
output   dst_7_ap_vld;
output  [31:0] dst_6;
output   dst_6_ap_vld;
output  [31:0] dst_5;
output   dst_5_ap_vld;
output  [31:0] dst_4;
output   dst_4_ap_vld;
output  [31:0] dst_3;
output   dst_3_ap_vld;
output  [31:0] dst_2;
output   dst_2_ap_vld;
output  [31:0] dst_1;
output   dst_1_ap_vld;
input  [31:0] src_0_val;
input  [31:0] src_1_val;
input  [31:0] src_2_val;
input  [31:0] src_3_val;
input  [31:0] src_4_val;
input  [31:0] src_5_val;
input  [31:0] src_6_val;
input  [31:0] src_7_val;
input  [31:0] src_8_val;
input  [31:0] src_9_val;
input  [31:0] src_10_val;
input  [31:0] src_11_val;
input  [31:0] src_12_val;
input  [31:0] src_13_val;
input  [31:0] src_14_val;
input  [31:0] src_15_val;
input  [31:0] conv3_i12_i_i;
input  [31:0] sh_prom_i9_i_i;
input  [31:0] sh_prom_i_i_i;
input  [0:0] empty_44;
input  [31:0] oMin;
input  [31:0] oMax;
input  [27:0] empty_45;
input  [31:0] cutoff;
input  [28:0] empty_46;
input  [29:0] empty_47;
input  [30:0] empty;

reg ap_idle;
reg dst_0_ap_vld;
reg dst_15_ap_vld;
reg dst_14_ap_vld;
reg dst_13_ap_vld;
reg dst_12_ap_vld;
reg dst_11_ap_vld;
reg dst_10_ap_vld;
reg dst_9_ap_vld;
reg dst_8_ap_vld;
reg dst_7_ap_vld;
reg dst_6_ap_vld;
reg dst_5_ap_vld;
reg dst_4_ap_vld;
reg dst_3_ap_vld;
reg dst_2_ap_vld;
reg dst_1_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln47_fu_884_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] p_ZL8idst7_16_0_address0;
wire   [6:0] p_ZL8idst7_16_0_q0;
wire   [3:0] p_ZL8idst7_16_1_address0;
wire  signed [7:0] p_ZL8idst7_16_1_q0;
wire   [3:0] p_ZL8idst7_16_2_address0;
wire  signed [7:0] p_ZL8idst7_16_2_q0;
wire   [3:0] p_ZL8idst7_16_3_address0;
wire  signed [7:0] p_ZL8idst7_16_3_q0;
wire   [3:0] p_ZL8idst7_16_4_address0;
wire  signed [7:0] p_ZL8idst7_16_4_q0;
wire   [3:0] p_ZL8idst7_16_5_address0;
wire  signed [7:0] p_ZL8idst7_16_5_q0;
wire   [3:0] p_ZL8idst7_16_6_address0;
wire  signed [7:0] p_ZL8idst7_16_6_q0;
wire   [3:0] p_ZL8idst7_16_7_address0;
wire  signed [7:0] p_ZL8idst7_16_7_q0;
wire   [3:0] p_ZL8idst7_16_8_address0;
wire  signed [7:0] p_ZL8idst7_16_8_q0;
wire   [3:0] p_ZL8idst7_16_9_address0;
wire   [7:0] p_ZL8idst7_16_9_q0;
wire   [3:0] p_ZL8idst7_16_10_address0;
wire   [7:0] p_ZL8idst7_16_10_q0;
wire   [3:0] p_ZL8idst7_16_11_address0;
wire   [7:0] p_ZL8idst7_16_11_q0;
wire   [3:0] p_ZL8idst7_16_12_address0;
wire   [7:0] p_ZL8idst7_16_12_q0;
wire   [3:0] p_ZL8idst7_16_13_address0;
wire   [7:0] p_ZL8idst7_16_13_q0;
wire   [3:0] p_ZL8idst7_16_14_address0;
wire   [7:0] p_ZL8idst7_16_14_q0;
wire   [3:0] p_ZL8idst7_16_15_address0;
wire   [7:0] p_ZL8idst7_16_15_q0;
wire    ap_block_pp0_stage0_11001;
wire   [32:0] sh_prom_i_i_i_cast_fu_768_p1;
reg   [32:0] sh_prom_i_i_i_cast_reg_1352;
wire   [32:0] sh_prom_i9_i_i_cast_fu_772_p1;
reg   [32:0] sh_prom_i9_i_i_cast_reg_1357;
wire  signed [32:0] conv3_i12_i_i_cast_fu_776_p1;
reg  signed [32:0] conv3_i12_i_i_cast_reg_1362;
wire   [0:0] icmp101_fu_780_p2;
reg   [0:0] icmp101_reg_1367;
wire   [0:0] cmp_i_i_14_fu_786_p2;
reg   [0:0] cmp_i_i_14_reg_1372;
wire   [0:0] cmp_i_i_13_fu_792_p2;
reg   [0:0] cmp_i_i_13_reg_1377;
wire   [0:0] cmp_i_i_12_fu_798_p2;
reg   [0:0] cmp_i_i_12_reg_1382;
wire   [0:0] cmp_i_i_11_fu_804_p2;
reg   [0:0] cmp_i_i_11_reg_1387;
wire   [0:0] cmp_i_i_10_fu_810_p2;
reg   [0:0] cmp_i_i_10_reg_1392;
wire   [0:0] cmp_i_i_9_fu_816_p2;
reg   [0:0] cmp_i_i_9_reg_1397;
wire   [0:0] cmp_i_i_8_fu_822_p2;
reg   [0:0] cmp_i_i_8_reg_1402;
wire   [0:0] icmp98_fu_828_p2;
reg   [0:0] icmp98_reg_1407;
wire   [0:0] cmp_i_i_6_fu_834_p2;
reg   [0:0] cmp_i_i_6_reg_1412;
wire   [0:0] cmp_i_i_5_fu_840_p2;
reg   [0:0] cmp_i_i_5_reg_1417;
wire   [0:0] cmp_i_i_4_fu_846_p2;
reg   [0:0] cmp_i_i_4_reg_1422;
wire   [0:0] icmp95_fu_852_p2;
reg   [0:0] icmp95_reg_1427;
wire   [0:0] cmp_i_i_2_fu_858_p2;
reg   [0:0] cmp_i_i_2_reg_1432;
wire   [0:0] icmp_fu_864_p2;
reg   [0:0] icmp_reg_1437;
wire   [0:0] cmp_i_i_fu_870_p2;
reg   [0:0] cmp_i_i_reg_1442;
wire   [63:0] zext_ln47_fu_896_p1;
reg   [63:0] zext_ln47_reg_1451;
wire   [3:0] trunc_ln47_fu_905_p1;
reg   [3:0] trunc_ln47_reg_1466;
reg   [3:0] trunc_ln47_reg_1466_pp0_iter1_reg;
reg   [3:0] trunc_ln47_reg_1466_pp0_iter2_reg;
reg   [3:0] trunc_ln47_reg_1466_pp0_iter3_reg;
reg   [3:0] trunc_ln47_reg_1466_pp0_iter4_reg;
wire   [31:0] sum_81_fu_937_p3;
reg   [31:0] sum_81_reg_1495;
wire   [31:0] sum_82_fu_949_p2;
reg   [31:0] sum_82_reg_1500;
wire   [31:0] mul_ln57_2_fu_716_p2;
reg   [31:0] mul_ln57_2_reg_1505;
wire   [31:0] mul_ln57_3_fu_720_p2;
reg   [31:0] mul_ln57_3_reg_1510;
wire   [31:0] sum_91_fu_1023_p3;
reg   [31:0] sum_91_reg_1570;
wire   [31:0] mul_ln57_6_fu_732_p2;
reg   [31:0] mul_ln57_6_reg_1576;
wire   [31:0] mul_ln57_7_fu_736_p2;
reg   [31:0] mul_ln57_7_reg_1581;
reg  signed [7:0] p_ZL8idst7_16_9_load_reg_1586;
reg  signed [7:0] p_ZL8idst7_16_10_load_reg_1591;
reg  signed [7:0] p_ZL8idst7_16_11_load_reg_1596;
reg  signed [7:0] p_ZL8idst7_16_12_load_reg_1601;
reg   [7:0] p_ZL8idst7_16_13_load_reg_1606;
reg  signed [7:0] p_ZL8idst7_16_13_load_reg_1606_pp0_iter3_reg;
reg   [7:0] p_ZL8idst7_16_14_load_reg_1611;
reg  signed [7:0] p_ZL8idst7_16_14_load_reg_1611_pp0_iter3_reg;
reg   [7:0] p_ZL8idst7_16_15_load_reg_1616;
reg  signed [7:0] p_ZL8idst7_16_15_load_reg_1616_pp0_iter3_reg;
wire   [31:0] sum_99_fu_1089_p3;
reg   [31:0] sum_99_reg_1621;
wire   [31:0] mul_ln57_10_fu_748_p2;
reg   [31:0] mul_ln57_10_reg_1627;
wire   [31:0] mul_ln57_11_fu_752_p2;
reg   [31:0] mul_ln57_11_reg_1632;
wire   [31:0] sum_107_fu_1153_p3;
reg   [31:0] sum_107_reg_1637;
wire   [31:0] mul_ln57_14_fu_764_p2;
reg   [31:0] mul_ln57_14_reg_1643;
wire    ap_block_pp0_stage0;
reg   [4:0] j_fu_218;
wire   [4:0] add_ln47_fu_890_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j_3;
wire   [31:0] select_ln8_fu_1225_p3;
wire    ap_block_pp0_stage0_01001;
reg    p_ZL8idst7_16_0_ce0_local;
reg    p_ZL8idst7_16_1_ce0_local;
reg    p_ZL8idst7_16_2_ce0_local;
reg    p_ZL8idst7_16_3_ce0_local;
reg    p_ZL8idst7_16_4_ce0_local;
reg    p_ZL8idst7_16_5_ce0_local;
reg    p_ZL8idst7_16_6_ce0_local;
reg    p_ZL8idst7_16_7_ce0_local;
reg    p_ZL8idst7_16_8_ce0_local;
reg    p_ZL8idst7_16_9_ce0_local;
reg    p_ZL8idst7_16_10_ce0_local;
reg    p_ZL8idst7_16_11_ce0_local;
reg    p_ZL8idst7_16_12_ce0_local;
reg    p_ZL8idst7_16_13_ce0_local;
reg    p_ZL8idst7_16_14_ce0_local;
reg    p_ZL8idst7_16_15_ce0_local;
wire   [6:0] sum_fu_704_p0;
wire   [31:0] sum_fu_704_p2;
wire   [31:0] mul_ln57_fu_708_p2;
wire   [31:0] sum_79_fu_919_p3;
wire   [31:0] sum_80_fu_931_p2;
wire   [31:0] mul_ln57_1_fu_712_p2;
wire   [31:0] sum_83_fu_965_p3;
wire   [31:0] sum_84_fu_970_p2;
wire   [31:0] sum_85_fu_975_p3;
wire   [31:0] sum_86_fu_982_p2;
wire   [31:0] mul_ln57_4_fu_724_p2;
wire   [31:0] sum_87_fu_987_p3;
wire   [31:0] sum_88_fu_999_p2;
wire   [31:0] mul_ln57_5_fu_728_p2;
wire   [31:0] sum_89_fu_1005_p3;
wire   [31:0] sum_90_fu_1017_p2;
wire   [31:0] sum_92_fu_1040_p2;
wire   [31:0] sum_93_fu_1044_p3;
wire   [31:0] sum_94_fu_1050_p2;
wire   [31:0] mul_ln57_8_fu_740_p2;
wire   [31:0] sum_95_fu_1055_p3;
wire   [31:0] sum_96_fu_1066_p2;
wire   [31:0] mul_ln57_9_fu_744_p2;
wire   [31:0] sum_97_fu_1072_p3;
wire   [31:0] sum_98_fu_1083_p2;
wire   [31:0] sum_100_fu_1104_p2;
wire   [31:0] sum_101_fu_1108_p3;
wire   [31:0] sum_102_fu_1114_p2;
wire   [31:0] mul_ln57_12_fu_756_p2;
wire   [31:0] sum_103_fu_1119_p3;
wire   [31:0] sum_104_fu_1130_p2;
wire   [31:0] mul_ln57_13_fu_760_p2;
wire   [31:0] sum_105_fu_1136_p3;
wire   [31:0] sum_106_fu_1147_p2;
wire   [31:0] sum_108_fu_1164_p2;
wire   [31:0] sum_109_fu_1168_p3;
wire  signed [32:0] sext_ln61_fu_1174_p1;
wire   [32:0] add_ln61_fu_1178_p2;
wire   [32:0] shl_ln61_fu_1183_p2;
wire   [32:0] ashr_ln61_fu_1188_p2;
wire   [31:0] trunc_ln61_fu_1193_p1;
wire   [31:0] trunc_ln61_1_fu_1197_p1;
wire   [31:0] scaled_fu_1201_p3;
wire   [0:0] icmp_ln9_fu_1213_p2;
wire   [0:0] icmp_ln8_fu_1208_p2;
wire   [31:0] select_ln9_fu_1218_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [31:0] sum_fu_704_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 j_fu_218 = 5'd0;
#0 ap_done_reg = 1'b0;
end

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_0_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_0_address0),
    .ce0(p_ZL8idst7_16_0_ce0_local),
    .q0(p_ZL8idst7_16_0_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_1_address0),
    .ce0(p_ZL8idst7_16_1_ce0_local),
    .q0(p_ZL8idst7_16_1_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_2_address0),
    .ce0(p_ZL8idst7_16_2_ce0_local),
    .q0(p_ZL8idst7_16_2_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_3_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_3_address0),
    .ce0(p_ZL8idst7_16_3_ce0_local),
    .q0(p_ZL8idst7_16_3_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_4_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_4_address0),
    .ce0(p_ZL8idst7_16_4_ce0_local),
    .q0(p_ZL8idst7_16_4_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_5_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_5_address0),
    .ce0(p_ZL8idst7_16_5_ce0_local),
    .q0(p_ZL8idst7_16_5_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_6_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_6_address0),
    .ce0(p_ZL8idst7_16_6_ce0_local),
    .q0(p_ZL8idst7_16_6_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_7_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_7_address0),
    .ce0(p_ZL8idst7_16_7_ce0_local),
    .q0(p_ZL8idst7_16_7_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_8_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_8_address0),
    .ce0(p_ZL8idst7_16_8_ce0_local),
    .q0(p_ZL8idst7_16_8_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_9_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_9_address0),
    .ce0(p_ZL8idst7_16_9_ce0_local),
    .q0(p_ZL8idst7_16_9_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_10_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_10_address0),
    .ce0(p_ZL8idst7_16_10_ce0_local),
    .q0(p_ZL8idst7_16_10_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_11_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_11_address0),
    .ce0(p_ZL8idst7_16_11_ce0_local),
    .q0(p_ZL8idst7_16_11_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_12_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_12_address0),
    .ce0(p_ZL8idst7_16_12_ce0_local),
    .q0(p_ZL8idst7_16_12_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_13_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_13_address0),
    .ce0(p_ZL8idst7_16_13_ce0_local),
    .q0(p_ZL8idst7_16_13_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_14_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_14_address0),
    .ce0(p_ZL8idst7_16_14_ce0_local),
    .q0(p_ZL8idst7_16_14_q0)
);

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1_p_ZL8idst7_16_15_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
p_ZL8idst7_16_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL8idst7_16_15_address0),
    .ce0(p_ZL8idst7_16_15_ce0_local),
    .q0(p_ZL8idst7_16_15_q0)
);

IDST7_mul_7ns_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_7ns_32s_32_1_1_U65(
    .din0(sum_fu_704_p0),
    .din1(src_0_val),
    .dout(sum_fu_704_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U66(
    .din0(p_ZL8idst7_16_1_q0),
    .din1(src_1_val),
    .dout(mul_ln57_fu_708_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U67(
    .din0(p_ZL8idst7_16_2_q0),
    .din1(src_2_val),
    .dout(mul_ln57_1_fu_712_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U68(
    .din0(p_ZL8idst7_16_3_q0),
    .din1(src_3_val),
    .dout(mul_ln57_2_fu_716_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U69(
    .din0(p_ZL8idst7_16_4_q0),
    .din1(src_4_val),
    .dout(mul_ln57_3_fu_720_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U70(
    .din0(p_ZL8idst7_16_5_q0),
    .din1(src_5_val),
    .dout(mul_ln57_4_fu_724_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U71(
    .din0(p_ZL8idst7_16_6_q0),
    .din1(src_6_val),
    .dout(mul_ln57_5_fu_728_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U72(
    .din0(p_ZL8idst7_16_7_q0),
    .din1(src_7_val),
    .dout(mul_ln57_6_fu_732_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U73(
    .din0(p_ZL8idst7_16_8_q0),
    .din1(src_8_val),
    .dout(mul_ln57_7_fu_736_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U74(
    .din0(p_ZL8idst7_16_9_load_reg_1586),
    .din1(src_9_val),
    .dout(mul_ln57_8_fu_740_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U75(
    .din0(p_ZL8idst7_16_10_load_reg_1591),
    .din1(src_10_val),
    .dout(mul_ln57_9_fu_744_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U76(
    .din0(p_ZL8idst7_16_11_load_reg_1596),
    .din1(src_11_val),
    .dout(mul_ln57_10_fu_748_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U77(
    .din0(p_ZL8idst7_16_12_load_reg_1601),
    .din1(src_12_val),
    .dout(mul_ln57_11_fu_752_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U78(
    .din0(p_ZL8idst7_16_13_load_reg_1606_pp0_iter3_reg),
    .din1(src_13_val),
    .dout(mul_ln57_12_fu_756_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U79(
    .din0(p_ZL8idst7_16_14_load_reg_1611_pp0_iter3_reg),
    .din1(src_14_val),
    .dout(mul_ln57_13_fu_760_p2)
);

IDST7_mul_8s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_8s_32s_32_1_1_U80(
    .din0(p_ZL8idst7_16_15_load_reg_1616_pp0_iter3_reg),
    .din1(src_15_val),
    .dout(mul_ln57_14_fu_764_p2)
);

IDST7_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln47_fu_884_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_218 <= add_ln47_fu_890_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_218 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp_i_i_10_reg_1392 <= cmp_i_i_10_fu_810_p2;
        cmp_i_i_11_reg_1387 <= cmp_i_i_11_fu_804_p2;
        cmp_i_i_12_reg_1382 <= cmp_i_i_12_fu_798_p2;
        cmp_i_i_13_reg_1377 <= cmp_i_i_13_fu_792_p2;
        cmp_i_i_14_reg_1372 <= cmp_i_i_14_fu_786_p2;
        cmp_i_i_2_reg_1432 <= cmp_i_i_2_fu_858_p2;
        cmp_i_i_4_reg_1422 <= cmp_i_i_4_fu_846_p2;
        cmp_i_i_5_reg_1417 <= cmp_i_i_5_fu_840_p2;
        cmp_i_i_6_reg_1412 <= cmp_i_i_6_fu_834_p2;
        cmp_i_i_8_reg_1402 <= cmp_i_i_8_fu_822_p2;
        cmp_i_i_9_reg_1397 <= cmp_i_i_9_fu_816_p2;
        cmp_i_i_reg_1442 <= cmp_i_i_fu_870_p2;
        conv3_i12_i_i_cast_reg_1362 <= conv3_i12_i_i_cast_fu_776_p1;
        icmp101_reg_1367 <= icmp101_fu_780_p2;
        icmp95_reg_1427 <= icmp95_fu_852_p2;
        icmp98_reg_1407 <= icmp98_fu_828_p2;
        icmp_reg_1437 <= icmp_fu_864_p2;
        mul_ln57_2_reg_1505 <= mul_ln57_2_fu_716_p2;
        mul_ln57_3_reg_1510 <= mul_ln57_3_fu_720_p2;
        sh_prom_i9_i_i_cast_reg_1357[31 : 0] <= sh_prom_i9_i_i_cast_fu_772_p1[31 : 0];
        sh_prom_i_i_i_cast_reg_1352[31 : 0] <= sh_prom_i_i_i_cast_fu_768_p1[31 : 0];
        sum_81_reg_1495 <= sum_81_fu_937_p3;
        sum_82_reg_1500 <= sum_82_fu_949_p2;
        trunc_ln47_reg_1466 <= trunc_ln47_fu_905_p1;
        trunc_ln47_reg_1466_pp0_iter1_reg <= trunc_ln47_reg_1466;
        zext_ln47_reg_1451[4 : 0] <= zext_ln47_fu_896_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        mul_ln57_10_reg_1627 <= mul_ln57_10_fu_748_p2;
        mul_ln57_11_reg_1632 <= mul_ln57_11_fu_752_p2;
        mul_ln57_14_reg_1643 <= mul_ln57_14_fu_764_p2;
        mul_ln57_6_reg_1576 <= mul_ln57_6_fu_732_p2;
        mul_ln57_7_reg_1581 <= mul_ln57_7_fu_736_p2;
        p_ZL8idst7_16_10_load_reg_1591 <= p_ZL8idst7_16_10_q0;
        p_ZL8idst7_16_11_load_reg_1596 <= p_ZL8idst7_16_11_q0;
        p_ZL8idst7_16_12_load_reg_1601 <= p_ZL8idst7_16_12_q0;
        p_ZL8idst7_16_13_load_reg_1606 <= p_ZL8idst7_16_13_q0;
        p_ZL8idst7_16_13_load_reg_1606_pp0_iter3_reg <= p_ZL8idst7_16_13_load_reg_1606;
        p_ZL8idst7_16_14_load_reg_1611 <= p_ZL8idst7_16_14_q0;
        p_ZL8idst7_16_14_load_reg_1611_pp0_iter3_reg <= p_ZL8idst7_16_14_load_reg_1611;
        p_ZL8idst7_16_15_load_reg_1616 <= p_ZL8idst7_16_15_q0;
        p_ZL8idst7_16_15_load_reg_1616_pp0_iter3_reg <= p_ZL8idst7_16_15_load_reg_1616;
        p_ZL8idst7_16_9_load_reg_1586 <= p_ZL8idst7_16_9_q0;
        sum_107_reg_1637 <= sum_107_fu_1153_p3;
        sum_91_reg_1570 <= sum_91_fu_1023_p3;
        sum_99_reg_1621 <= sum_99_fu_1089_p3;
        trunc_ln47_reg_1466_pp0_iter2_reg <= trunc_ln47_reg_1466_pp0_iter1_reg;
        trunc_ln47_reg_1466_pp0_iter3_reg <= trunc_ln47_reg_1466_pp0_iter2_reg;
        trunc_ln47_reg_1466_pp0_iter4_reg <= trunc_ln47_reg_1466_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_884_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_3 = 5'd0;
    end else begin
        ap_sig_allocacmp_j_3 = j_fu_218;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_0_ap_vld = 1'b1;
    end else begin
        dst_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd10) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_10_ap_vld = 1'b1;
    end else begin
        dst_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd11) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_11_ap_vld = 1'b1;
    end else begin
        dst_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd12) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_12_ap_vld = 1'b1;
    end else begin
        dst_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd13) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_13_ap_vld = 1'b1;
    end else begin
        dst_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd14) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_14_ap_vld = 1'b1;
    end else begin
        dst_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd15) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_15_ap_vld = 1'b1;
    end else begin
        dst_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_1_ap_vld = 1'b1;
    end else begin
        dst_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd2) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_2_ap_vld = 1'b1;
    end else begin
        dst_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd3) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_3_ap_vld = 1'b1;
    end else begin
        dst_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd4) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_4_ap_vld = 1'b1;
    end else begin
        dst_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd5) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_5_ap_vld = 1'b1;
    end else begin
        dst_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd6) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_6_ap_vld = 1'b1;
    end else begin
        dst_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd7) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_7_ap_vld = 1'b1;
    end else begin
        dst_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd8) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_8_ap_vld = 1'b1;
    end else begin
        dst_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln47_reg_1466_pp0_iter4_reg == 4'd9) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        dst_9_ap_vld = 1'b1;
    end else begin
        dst_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_0_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_10_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_11_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_12_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_13_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_14_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_15_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_1_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_2_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_3_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_4_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_5_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_6_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_7_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_8_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL8idst7_16_9_ce0_local = 1'b1;
    end else begin
        p_ZL8idst7_16_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln47_fu_890_p2 = (ap_sig_allocacmp_j_3 + 5'd1);

assign add_ln61_fu_1178_p2 = ($signed(sext_ln61_fu_1174_p1) + $signed(conv3_i12_i_i_cast_reg_1362));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign ashr_ln61_fu_1188_p2 = $signed(add_ln61_fu_1178_p2) >>> sh_prom_i_i_i_cast_reg_1352;

assign cmp_i_i_10_fu_810_p2 = (($signed(cutoff) > $signed(32'd10)) ? 1'b1 : 1'b0);

assign cmp_i_i_11_fu_804_p2 = (($signed(cutoff) > $signed(32'd11)) ? 1'b1 : 1'b0);

assign cmp_i_i_12_fu_798_p2 = (($signed(cutoff) > $signed(32'd12)) ? 1'b1 : 1'b0);

assign cmp_i_i_13_fu_792_p2 = (($signed(cutoff) > $signed(32'd13)) ? 1'b1 : 1'b0);

assign cmp_i_i_14_fu_786_p2 = (($signed(cutoff) > $signed(32'd14)) ? 1'b1 : 1'b0);

assign cmp_i_i_2_fu_858_p2 = (($signed(cutoff) > $signed(32'd2)) ? 1'b1 : 1'b0);

assign cmp_i_i_4_fu_846_p2 = (($signed(cutoff) > $signed(32'd4)) ? 1'b1 : 1'b0);

assign cmp_i_i_5_fu_840_p2 = (($signed(cutoff) > $signed(32'd5)) ? 1'b1 : 1'b0);

assign cmp_i_i_6_fu_834_p2 = (($signed(cutoff) > $signed(32'd6)) ? 1'b1 : 1'b0);

assign cmp_i_i_8_fu_822_p2 = (($signed(cutoff) > $signed(32'd8)) ? 1'b1 : 1'b0);

assign cmp_i_i_9_fu_816_p2 = (($signed(cutoff) > $signed(32'd9)) ? 1'b1 : 1'b0);

assign cmp_i_i_fu_870_p2 = (($signed(cutoff) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign conv3_i12_i_i_cast_fu_776_p1 = $signed(conv3_i12_i_i);

assign dst_0 = select_ln8_fu_1225_p3;

assign dst_1 = select_ln8_fu_1225_p3;

assign dst_10 = select_ln8_fu_1225_p3;

assign dst_11 = select_ln8_fu_1225_p3;

assign dst_12 = select_ln8_fu_1225_p3;

assign dst_13 = select_ln8_fu_1225_p3;

assign dst_14 = select_ln8_fu_1225_p3;

assign dst_15 = select_ln8_fu_1225_p3;

assign dst_2 = select_ln8_fu_1225_p3;

assign dst_3 = select_ln8_fu_1225_p3;

assign dst_4 = select_ln8_fu_1225_p3;

assign dst_5 = select_ln8_fu_1225_p3;

assign dst_6 = select_ln8_fu_1225_p3;

assign dst_7 = select_ln8_fu_1225_p3;

assign dst_8 = select_ln8_fu_1225_p3;

assign dst_9 = select_ln8_fu_1225_p3;

assign icmp101_fu_780_p2 = (($signed(empty_45) > $signed(28'd0)) ? 1'b1 : 1'b0);

assign icmp95_fu_852_p2 = (($signed(empty_47) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp98_fu_828_p2 = (($signed(empty_46) > $signed(29'd0)) ? 1'b1 : 1'b0);

assign icmp_fu_864_p2 = (($signed(empty) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_884_p2 = ((ap_sig_allocacmp_j_3 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_1208_p2 = (($signed(scaled_fu_1201_p3) < $signed(oMin)) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_1213_p2 = (($signed(scaled_fu_1201_p3) > $signed(oMax)) ? 1'b1 : 1'b0);

assign p_ZL8idst7_16_0_address0 = zext_ln47_fu_896_p1;

assign p_ZL8idst7_16_10_address0 = zext_ln47_reg_1451;

assign p_ZL8idst7_16_11_address0 = zext_ln47_reg_1451;

assign p_ZL8idst7_16_12_address0 = zext_ln47_reg_1451;

assign p_ZL8idst7_16_13_address0 = zext_ln47_reg_1451;

assign p_ZL8idst7_16_14_address0 = zext_ln47_reg_1451;

assign p_ZL8idst7_16_15_address0 = zext_ln47_reg_1451;

assign p_ZL8idst7_16_1_address0 = zext_ln47_fu_896_p1;

assign p_ZL8idst7_16_2_address0 = zext_ln47_fu_896_p1;

assign p_ZL8idst7_16_3_address0 = zext_ln47_fu_896_p1;

assign p_ZL8idst7_16_4_address0 = zext_ln47_fu_896_p1;

assign p_ZL8idst7_16_5_address0 = zext_ln47_reg_1451;

assign p_ZL8idst7_16_6_address0 = zext_ln47_reg_1451;

assign p_ZL8idst7_16_7_address0 = zext_ln47_reg_1451;

assign p_ZL8idst7_16_8_address0 = zext_ln47_reg_1451;

assign p_ZL8idst7_16_9_address0 = zext_ln47_reg_1451;

assign scaled_fu_1201_p3 = ((empty_44[0:0] == 1'b1) ? trunc_ln61_fu_1193_p1 : trunc_ln61_1_fu_1197_p1);

assign select_ln8_fu_1225_p3 = ((icmp_ln8_fu_1208_p2[0:0] == 1'b1) ? oMin : select_ln9_fu_1218_p3);

assign select_ln9_fu_1218_p3 = ((icmp_ln9_fu_1213_p2[0:0] == 1'b1) ? oMax : scaled_fu_1201_p3);

assign sext_ln61_fu_1174_p1 = $signed(sum_109_fu_1168_p3);

assign sh_prom_i9_i_i_cast_fu_772_p1 = sh_prom_i9_i_i;

assign sh_prom_i_i_i_cast_fu_768_p1 = sh_prom_i_i_i;

assign shl_ln61_fu_1183_p2 = add_ln61_fu_1178_p2 << sh_prom_i9_i_i_cast_reg_1357;

assign sum_100_fu_1104_p2 = (mul_ln57_10_reg_1627 + sum_99_reg_1621);

assign sum_101_fu_1108_p3 = ((cmp_i_i_11_reg_1387[0:0] == 1'b1) ? sum_100_fu_1104_p2 : sum_99_reg_1621);

assign sum_102_fu_1114_p2 = (mul_ln57_11_reg_1632 + sum_101_fu_1108_p3);

assign sum_103_fu_1119_p3 = ((cmp_i_i_12_reg_1382[0:0] == 1'b1) ? sum_102_fu_1114_p2 : sum_101_fu_1108_p3);

assign sum_104_fu_1130_p2 = (mul_ln57_12_fu_756_p2 + sum_103_fu_1119_p3);

assign sum_105_fu_1136_p3 = ((cmp_i_i_13_reg_1377[0:0] == 1'b1) ? sum_104_fu_1130_p2 : sum_103_fu_1119_p3);

assign sum_106_fu_1147_p2 = (mul_ln57_13_fu_760_p2 + sum_105_fu_1136_p3);

assign sum_107_fu_1153_p3 = ((cmp_i_i_14_reg_1372[0:0] == 1'b1) ? sum_106_fu_1147_p2 : sum_105_fu_1136_p3);

assign sum_108_fu_1164_p2 = (mul_ln57_14_reg_1643 + sum_107_reg_1637);

assign sum_109_fu_1168_p3 = ((icmp101_reg_1367[0:0] == 1'b1) ? sum_108_fu_1164_p2 : sum_107_reg_1637);

assign sum_79_fu_919_p3 = ((cmp_i_i_reg_1442[0:0] == 1'b1) ? sum_fu_704_p2 : 32'd0);

assign sum_80_fu_931_p2 = (mul_ln57_fu_708_p2 + sum_79_fu_919_p3);

assign sum_81_fu_937_p3 = ((icmp_reg_1437[0:0] == 1'b1) ? sum_80_fu_931_p2 : sum_79_fu_919_p3);

assign sum_82_fu_949_p2 = (mul_ln57_1_fu_712_p2 + sum_81_fu_937_p3);

assign sum_83_fu_965_p3 = ((cmp_i_i_2_reg_1432[0:0] == 1'b1) ? sum_82_reg_1500 : sum_81_reg_1495);

assign sum_84_fu_970_p2 = (mul_ln57_2_reg_1505 + sum_83_fu_965_p3);

assign sum_85_fu_975_p3 = ((icmp95_reg_1427[0:0] == 1'b1) ? sum_84_fu_970_p2 : sum_83_fu_965_p3);

assign sum_86_fu_982_p2 = (mul_ln57_3_reg_1510 + sum_85_fu_975_p3);

assign sum_87_fu_987_p3 = ((cmp_i_i_4_reg_1422[0:0] == 1'b1) ? sum_86_fu_982_p2 : sum_85_fu_975_p3);

assign sum_88_fu_999_p2 = (mul_ln57_4_fu_724_p2 + sum_87_fu_987_p3);

assign sum_89_fu_1005_p3 = ((cmp_i_i_5_reg_1417[0:0] == 1'b1) ? sum_88_fu_999_p2 : sum_87_fu_987_p3);

assign sum_90_fu_1017_p2 = (mul_ln57_5_fu_728_p2 + sum_89_fu_1005_p3);

assign sum_91_fu_1023_p3 = ((cmp_i_i_6_reg_1412[0:0] == 1'b1) ? sum_90_fu_1017_p2 : sum_89_fu_1005_p3);

assign sum_92_fu_1040_p2 = (mul_ln57_6_reg_1576 + sum_91_reg_1570);

assign sum_93_fu_1044_p3 = ((icmp98_reg_1407[0:0] == 1'b1) ? sum_92_fu_1040_p2 : sum_91_reg_1570);

assign sum_94_fu_1050_p2 = (mul_ln57_7_reg_1581 + sum_93_fu_1044_p3);

assign sum_95_fu_1055_p3 = ((cmp_i_i_8_reg_1402[0:0] == 1'b1) ? sum_94_fu_1050_p2 : sum_93_fu_1044_p3);

assign sum_96_fu_1066_p2 = (mul_ln57_8_fu_740_p2 + sum_95_fu_1055_p3);

assign sum_97_fu_1072_p3 = ((cmp_i_i_9_reg_1397[0:0] == 1'b1) ? sum_96_fu_1066_p2 : sum_95_fu_1055_p3);

assign sum_98_fu_1083_p2 = (mul_ln57_9_fu_744_p2 + sum_97_fu_1072_p3);

assign sum_99_fu_1089_p3 = ((cmp_i_i_10_reg_1392[0:0] == 1'b1) ? sum_98_fu_1083_p2 : sum_97_fu_1072_p3);

assign sum_fu_704_p0 = sum_fu_704_p00;

assign sum_fu_704_p00 = p_ZL8idst7_16_0_q0;

assign trunc_ln47_fu_905_p1 = ap_sig_allocacmp_j_3[3:0];

assign trunc_ln61_1_fu_1197_p1 = ashr_ln61_fu_1188_p2[31:0];

assign trunc_ln61_fu_1193_p1 = shl_ln61_fu_1183_p2[31:0];

assign zext_ln47_fu_896_p1 = ap_sig_allocacmp_j_3;

always @ (posedge ap_clk) begin
    sh_prom_i_i_i_cast_reg_1352[32] <= 1'b0;
    sh_prom_i9_i_i_cast_reg_1357[32] <= 1'b0;
    zext_ln47_reg_1451[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1
