-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity IDCT8_IDCT8B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idct8_32_18_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of IDCT8_IDCT8B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idct8_32_18_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111000", 1 => "10110000", 2 => "11101011", 3 => "01011010", 
    4 => "11101111", 5 => "10101110", 6 => "00110101", 7 => "00111100", 
    8 => "10110010", 9 => "11100110", 10 => "01011010", 11 => "11110011", 
    12 => "10101100", 13 => "00110010", 14 => "00111111", 15 => "10110011", 
    16 => "11100010", 17 => "01011001", 18 => "11110111", 19 => "10101011", 
    20 => "00101110", 21 => "01000010", 22 => "10110110", 23 => "11011110", 
    24 => "01011000", 25 => "11111100", 26 => "10101010", 27 => "00101010", 
    28 => "01000100", 29 => "10111000", 30 => "11011010", 31 => "01010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

