-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity IDCT8_IDCT8B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idct8_32_6_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of IDCT8_IDCT8B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idct8_32_6_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "01010101", 1 => "00110101", 2 => "00000000", 3 => "11001011", 
    4 => "10101011", 5 => "10101011", 6 => "11001011", 7 => "00000000", 
    8 => "00110101", 9 => "01010101", 10 => "01010101", 11 => "00110101", 
    12 => "00000000", 13 => "11001011", 14 => "10101011", 15 => "10101011", 
    16 => "11001011", 17 => "00000000", 18 => "00110101", 19 => "01010101", 
    20 => "01010101", 21 => "00110101", 22 => "00000000", 23 => "11001011", 
    24 => "10101011", 25 => "10101011", 26 => "11001011", 27 => "00000000", 
    28 => "00110101", 29 => "01010101", 30 => "01010101", 31 => "00110101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

