-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity IDST7_IDST7B16 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
    src_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
    dst_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_0_ap_vld : OUT STD_LOGIC;
    dst_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_1_ap_vld : OUT STD_LOGIC;
    dst_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_2_ap_vld : OUT STD_LOGIC;
    dst_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_3_ap_vld : OUT STD_LOGIC;
    dst_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_4_ap_vld : OUT STD_LOGIC;
    dst_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_5_ap_vld : OUT STD_LOGIC;
    dst_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_6_ap_vld : OUT STD_LOGIC;
    dst_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_7_ap_vld : OUT STD_LOGIC;
    dst_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_8_ap_vld : OUT STD_LOGIC;
    dst_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_9_ap_vld : OUT STD_LOGIC;
    dst_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_10_ap_vld : OUT STD_LOGIC;
    dst_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_11_ap_vld : OUT STD_LOGIC;
    dst_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_12_ap_vld : OUT STD_LOGIC;
    dst_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_13_ap_vld : OUT STD_LOGIC;
    dst_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_14_ap_vld : OUT STD_LOGIC;
    dst_15 : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_15_ap_vld : OUT STD_LOGIC;
    shift : IN STD_LOGIC_VECTOR (31 downto 0);
    skipLine2 : IN STD_LOGIC_VECTOR (31 downto 0);
    oMin : IN STD_LOGIC_VECTOR (31 downto 0);
    oMax : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of IDST7_IDST7B16 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv33_1FFFFFFFF : STD_LOGIC_VECTOR (32 downto 0) := "111111111111111111111111111111111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal rndFactor_6_fu_412_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rndFactor_6_reg_583 : STD_LOGIC_VECTOR (31 downto 0);
    signal cutoff_fu_421_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cutoff_reg_588 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_23_reg_593 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_i_i_i_i_fu_437_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_i_i_i_i_reg_598 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_reg_603 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_25_reg_608 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_26_reg_613 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_27_reg_618 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_idle : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_ready : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld : STD_LOGIC;
    signal grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg : STD_LOGIC := '0';
    signal dst_0_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal dst_15_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_14_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_13_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_12_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_11_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln43_fu_372_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln43_fu_372_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln43_fu_376_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln43_fu_390_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln43_fu_394_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_382_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal rndFactor_fu_400_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rndFactor_5_fu_406_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_23_fu_428_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_i_i_i_i_fu_437_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dst_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_0_ap_vld : OUT STD_LOGIC;
        dst_15 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_15_ap_vld : OUT STD_LOGIC;
        dst_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_14_ap_vld : OUT STD_LOGIC;
        dst_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_13_ap_vld : OUT STD_LOGIC;
        dst_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_12_ap_vld : OUT STD_LOGIC;
        dst_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_11_ap_vld : OUT STD_LOGIC;
        dst_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_10_ap_vld : OUT STD_LOGIC;
        dst_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_9_ap_vld : OUT STD_LOGIC;
        dst_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_8_ap_vld : OUT STD_LOGIC;
        dst_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_7_ap_vld : OUT STD_LOGIC;
        dst_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_6_ap_vld : OUT STD_LOGIC;
        dst_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_5_ap_vld : OUT STD_LOGIC;
        dst_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_4_ap_vld : OUT STD_LOGIC;
        dst_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_3_ap_vld : OUT STD_LOGIC;
        dst_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_2_ap_vld : OUT STD_LOGIC;
        dst_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        dst_1_ap_vld : OUT STD_LOGIC;
        src_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
        src_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
        conv3_i12_i_i : IN STD_LOGIC_VECTOR (31 downto 0);
        sh_prom_i9_i_i : IN STD_LOGIC_VECTOR (31 downto 0);
        sh_prom_i_i_i : IN STD_LOGIC_VECTOR (31 downto 0);
        empty_44 : IN STD_LOGIC_VECTOR (0 downto 0);
        oMin : IN STD_LOGIC_VECTOR (31 downto 0);
        oMax : IN STD_LOGIC_VECTOR (31 downto 0);
        empty_45 : IN STD_LOGIC_VECTOR (27 downto 0);
        cutoff : IN STD_LOGIC_VECTOR (31 downto 0);
        empty_46 : IN STD_LOGIC_VECTOR (28 downto 0);
        empty_47 : IN STD_LOGIC_VECTOR (29 downto 0);
        empty : IN STD_LOGIC_VECTOR (30 downto 0) );
    end component;



begin
    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258 : component IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start,
        ap_done => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done,
        ap_idle => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_idle,
        ap_ready => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_ready,
        dst_0 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0,
        dst_0_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld,
        dst_15 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15,
        dst_15_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld,
        dst_14 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14,
        dst_14_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld,
        dst_13 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13,
        dst_13_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld,
        dst_12 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12,
        dst_12_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld,
        dst_11 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11,
        dst_11_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld,
        dst_10 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10,
        dst_10_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld,
        dst_9 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9,
        dst_9_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld,
        dst_8 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8,
        dst_8_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld,
        dst_7 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7,
        dst_7_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld,
        dst_6 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6,
        dst_6_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld,
        dst_5 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5,
        dst_5_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld,
        dst_4 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4,
        dst_4_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld,
        dst_3 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3,
        dst_3_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld,
        dst_2 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2,
        dst_2_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld,
        dst_1 => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1,
        dst_1_ap_vld => grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld,
        src_0_val => src_0_val,
        src_1_val => src_1_val,
        src_2_val => src_2_val,
        src_3_val => src_3_val,
        src_4_val => src_4_val,
        src_5_val => src_5_val,
        src_6_val => src_6_val,
        src_7_val => src_7_val,
        src_8_val => src_8_val,
        src_9_val => src_9_val,
        src_10_val => src_10_val,
        src_11_val => src_11_val,
        src_12_val => src_12_val,
        src_13_val => src_13_val,
        src_14_val => src_14_val,
        src_15_val => src_15_val,
        conv3_i12_i_i => rndFactor_6_reg_583,
        sh_prom_i9_i_i => sub_i_i_i_i_reg_598,
        sh_prom_i_i_i => shift,
        empty_44 => tmp_23_reg_593,
        oMin => oMin,
        oMax => oMax,
        empty_45 => tmp_27_reg_618,
        cutoff => cutoff_reg_588,
        empty_46 => tmp_26_reg_613,
        empty_47 => tmp_25_reg_608,
        empty => tmp_24_reg_603);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_ready = ap_const_logic_1)) then 
                    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                cutoff_reg_588 <= cutoff_fu_421_p2;
                rndFactor_6_reg_583 <= rndFactor_6_fu_412_p3;
                sub_i_i_i_i_reg_598 <= sub_i_i_i_i_fu_437_p2;
                tmp_23_reg_593 <= tmp_23_fu_428_p1(31 downto 31);
                tmp_24_reg_603 <= cutoff_fu_421_p2(31 downto 1);
                tmp_25_reg_608 <= cutoff_fu_421_p2(31 downto 2);
                tmp_26_reg_613 <= cutoff_fu_421_p2(31 downto 3);
                tmp_27_reg_618 <= cutoff_fu_421_p2(31 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld = ap_const_logic_1))) then
                dst_0_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld = ap_const_logic_1))) then
                dst_10_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld = ap_const_logic_1))) then
                dst_11_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld = ap_const_logic_1))) then
                dst_12_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld = ap_const_logic_1))) then
                dst_13_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld = ap_const_logic_1))) then
                dst_14_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld = ap_const_logic_1))) then
                dst_15_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld = ap_const_logic_1))) then
                dst_1_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld = ap_const_logic_1))) then
                dst_2_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld = ap_const_logic_1))) then
                dst_3_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld = ap_const_logic_1))) then
                dst_4_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld = ap_const_logic_1))) then
                dst_5_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld = ap_const_logic_1))) then
                dst_6_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld = ap_const_logic_1))) then
                dst_7_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld = ap_const_logic_1))) then
                dst_8_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld = ap_const_logic_1))) then
                dst_9_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln43_fu_376_p2 <= std_logic_vector(signed(sext_ln43_fu_372_p1) + signed(ap_const_lv33_1FFFFFFFF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done)
    begin
        if ((grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cutoff_fu_421_p2 <= std_logic_vector(unsigned(ap_const_lv32_10) - unsigned(skipLine2));

    dst_0_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld, dst_0_reg, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld = ap_const_logic_1))) then 
            dst_0 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0;
        else 
            dst_0 <= dst_0_reg;
        end if; 
    end process;

    dst_0_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld;

    dst_1_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld, ap_CS_fsm_state2, dst_1_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld = ap_const_logic_1))) then 
            dst_1 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1;
        else 
            dst_1 <= dst_1_reg;
        end if; 
    end process;


    dst_10_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld, ap_CS_fsm_state2, dst_10_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld = ap_const_logic_1))) then 
            dst_10 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10;
        else 
            dst_10 <= dst_10_reg;
        end if; 
    end process;

    dst_10_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld;

    dst_11_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld, ap_CS_fsm_state2, dst_11_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld = ap_const_logic_1))) then 
            dst_11 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11;
        else 
            dst_11 <= dst_11_reg;
        end if; 
    end process;

    dst_11_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld;

    dst_12_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld, ap_CS_fsm_state2, dst_12_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld = ap_const_logic_1))) then 
            dst_12 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12;
        else 
            dst_12 <= dst_12_reg;
        end if; 
    end process;

    dst_12_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld;

    dst_13_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld, ap_CS_fsm_state2, dst_13_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld = ap_const_logic_1))) then 
            dst_13 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13;
        else 
            dst_13 <= dst_13_reg;
        end if; 
    end process;

    dst_13_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld;

    dst_14_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld, ap_CS_fsm_state2, dst_14_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld = ap_const_logic_1))) then 
            dst_14 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14;
        else 
            dst_14 <= dst_14_reg;
        end if; 
    end process;

    dst_14_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld;

    dst_15_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld, ap_CS_fsm_state2, dst_15_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld = ap_const_logic_1))) then 
            dst_15 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15;
        else 
            dst_15 <= dst_15_reg;
        end if; 
    end process;

    dst_15_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld;
    dst_1_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld;

    dst_2_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld, ap_CS_fsm_state2, dst_2_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld = ap_const_logic_1))) then 
            dst_2 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2;
        else 
            dst_2 <= dst_2_reg;
        end if; 
    end process;

    dst_2_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld;

    dst_3_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld, ap_CS_fsm_state2, dst_3_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld = ap_const_logic_1))) then 
            dst_3 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3;
        else 
            dst_3 <= dst_3_reg;
        end if; 
    end process;

    dst_3_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld;

    dst_4_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld, ap_CS_fsm_state2, dst_4_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld = ap_const_logic_1))) then 
            dst_4 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4;
        else 
            dst_4 <= dst_4_reg;
        end if; 
    end process;

    dst_4_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld;

    dst_5_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld, ap_CS_fsm_state2, dst_5_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld = ap_const_logic_1))) then 
            dst_5 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5;
        else 
            dst_5 <= dst_5_reg;
        end if; 
    end process;

    dst_5_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld;

    dst_6_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld, ap_CS_fsm_state2, dst_6_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld = ap_const_logic_1))) then 
            dst_6 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6;
        else 
            dst_6 <= dst_6_reg;
        end if; 
    end process;

    dst_6_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld;

    dst_7_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld, ap_CS_fsm_state2, dst_7_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld = ap_const_logic_1))) then 
            dst_7 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7;
        else 
            dst_7 <= dst_7_reg;
        end if; 
    end process;

    dst_7_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld;

    dst_8_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld, ap_CS_fsm_state2, dst_8_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld = ap_const_logic_1))) then 
            dst_8 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8;
        else 
            dst_8 <= dst_8_reg;
        end if; 
    end process;

    dst_8_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld;

    dst_9_assign_proc : process(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9, grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld, ap_CS_fsm_state2, dst_9_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld = ap_const_logic_1))) then 
            dst_9 <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9;
        else 
            dst_9 <= dst_9_reg;
        end if; 
    end process;

    dst_9_ap_vld <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld;
    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg;
    rndFactor_5_fu_406_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & trunc_ln43_fu_390_p1(31-1 downto 0)))));
    rndFactor_6_fu_412_p3 <= 
        rndFactor_fu_400_p2 when (tmp_fu_382_p3(0) = '1') else 
        rndFactor_5_fu_406_p2;
    rndFactor_fu_400_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv32_1),to_integer(unsigned('0' & sub_ln43_fu_394_p2(31-1 downto 0)))));
    sext_ln43_fu_372_p0 <= shift;
        sext_ln43_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln43_fu_372_p0),33));

    sub_i_i_i_i_fu_437_p1 <= shift;
    sub_i_i_i_i_fu_437_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(sub_i_i_i_i_fu_437_p1));
    sub_ln43_fu_394_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(trunc_ln43_fu_390_p1));
    tmp_23_fu_428_p1 <= shift;
    tmp_fu_382_p3 <= add_ln43_fu_376_p2(32 downto 32);
    trunc_ln43_fu_390_p1 <= add_ln43_fu_376_p2(32 - 1 downto 0);
end behav;
