-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity IDCT2_IDCT2B16 is
port (
    ap_ready : OUT STD_LOGIC;
    in_0_val : IN STD_LOGIC_VECTOR (25 downto 0);
    in_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_8_val : IN STD_LOGIC_VECTOR (25 downto 0);
    in_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of IDCT2_IDCT2B16 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_FFFFFFD5 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111010101";
    constant ap_const_lv32_FFFFFFA6 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111110100110";
    constant ap_const_lv32_FFFFFFBA : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111110111010";
    constant ap_const_lv32_FFFFFFE7 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111100111";
    constant ap_const_lv32_FFFFFFA9 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111110101001";
    constant ap_const_lv32_FFFFFFC7 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111000111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal call_ret_IDCT2B8_fu_164_ap_ready : STD_LOGIC;
    signal call_ret_IDCT2B8_fu_164_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B8_fu_164_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B8_fu_164_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B8_fu_164_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B8_fu_164_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B8_fu_164_ap_return_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B8_fu_164_ap_return_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B8_fu_164_ap_return_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_fu_184_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln103_1_fu_190_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln103_2_fu_196_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln103_3_fu_202_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln103_4_fu_208_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln103_5_fu_214_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln103_6_fu_220_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln103_7_fu_226_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln103_8_fu_232_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln103_9_fu_238_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln103_10_fu_244_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln103_11_fu_250_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln103_12_fu_256_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln103_13_fu_262_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln103_14_fu_268_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln103_15_fu_274_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln103_16_fu_280_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln103_17_fu_286_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln103_18_fu_292_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln103_fu_330_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_1_fu_336_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_fu_342_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_2_fu_348_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_1_fu_354_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_3_fu_360_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_4_fu_372_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_5_fu_378_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_4_fu_372_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_5_fu_378_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_6_fu_390_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_2_fu_384_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_6_fu_390_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_3_fu_396_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_4_fu_402_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_7_fu_408_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_8_fu_414_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_7_fu_408_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_8_fu_414_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_9_fu_426_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_10_fu_432_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_9_fu_426_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_10_fu_432_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_11_fu_444_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_58_fu_438_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_11_fu_444_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_12_fu_456_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_13_fu_462_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_12_fu_456_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_13_fu_462_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_6_fu_468_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_59_fu_474_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_14_fu_480_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_15_fu_486_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_14_fu_480_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_15_fu_486_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_16_fu_498_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_7_fu_492_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_16_fu_498_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_8_fu_504_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_9_fu_510_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_17_fu_516_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_18_fu_522_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_17_fu_516_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_18_fu_522_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_10_fu_528_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_60_fu_534_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_19_fu_540_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_19_fu_540_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_61_fu_546_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_9_fu_510_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_60_fu_534_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_59_fu_474_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_5_fu_450_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_1_fu_558_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_fu_552_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_4_fu_402_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_57_fu_420_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_56_fu_366_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_61_fu_546_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_4_fu_576_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_3_fu_570_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_5_fu_582_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_2_fu_564_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_20_fu_600_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_20_fu_600_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_12_fu_606_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_62_fu_612_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_21_fu_618_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_21_fu_618_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_63_fu_624_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_22_fu_636_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_13_fu_630_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_22_fu_636_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_1_fu_190_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_2_fu_196_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_14_fu_642_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_fu_184_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_8_fu_654_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_7_fu_648_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_62_fu_612_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_63_fu_624_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_11_fu_594_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_3_fu_202_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_11_fu_672_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_10_fu_666_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_12_fu_678_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_9_fu_660_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_23_fu_690_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_24_fu_696_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_65_fu_708_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_25_fu_714_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_25_fu_714_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_15_fu_720_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_66_fu_726_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_26_fu_732_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_26_fu_732_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_16_fu_738_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_27_fu_750_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_17_fu_744_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_27_fu_750_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_28_fu_762_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_29_fu_768_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_28_fu_762_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_29_fu_768_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_30_fu_780_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_18_fu_774_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_30_fu_780_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_19_fu_786_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_20_fu_792_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_66_fu_726_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_67_fu_756_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_6_fu_220_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_5_fu_214_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_15_fu_804_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_14_fu_798_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_65_fu_708_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_4_fu_208_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_64_fu_702_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_20_fu_792_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_18_fu_822_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_17_fu_816_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_19_fu_828_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_16_fu_810_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_68_fu_840_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_69_fu_852_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_31_fu_858_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_32_fu_864_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_31_fu_858_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_32_fu_864_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_22_fu_870_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_33_fu_882_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_23_fu_876_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_33_fu_882_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_34_fu_894_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_34_fu_894_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_24_fu_900_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_71_fu_906_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_35_fu_912_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_35_fu_912_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_36_fu_924_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_25_fu_918_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_36_fu_924_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_71_fu_906_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_26_fu_930_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_70_fu_888_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_69_fu_852_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_22_fu_942_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_21_fu_936_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_7_fu_226_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_8_fu_232_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_21_fu_846_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_9_fu_238_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_25_fu_960_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_24_fu_954_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_26_fu_966_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_23_fu_948_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_27_fu_978_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_37_fu_996_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_28_fu_990_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_37_fu_996_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_38_fu_1008_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_39_fu_1014_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_38_fu_1008_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_39_fu_1014_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_30_fu_1020_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_31_fu_1026_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_32_fu_1038_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_33_fu_1044_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_40_fu_1056_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_34_fu_1050_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_40_fu_1056_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_35_fu_1062_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_36_fu_1068_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_41_fu_1080_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_74_fu_1074_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_41_fu_1080_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_11_fu_250_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_36_fu_1068_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_33_fu_1044_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_73_fu_1032_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_29_fu_1098_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_28_fu_1092_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_29_fu_1002_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_10_fu_244_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_72_fu_984_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_37_fu_1086_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_32_fu_1116_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_31_fu_1110_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_33_fu_1122_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_30_fu_1104_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_38_fu_1134_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_42_fu_1140_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_39_fu_1146_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_41_fu_1158_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_75_fu_1164_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_42_fu_1170_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_76_fu_1176_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_43_fu_1188_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_77_fu_1182_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_43_fu_1188_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_78_fu_1200_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_44_fu_1206_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_43_fu_1194_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_78_fu_1200_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_13_fu_262_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_76_fu_1176_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_36_fu_1224_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_35_fu_1218_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_12_fu_256_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_75_fu_1164_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_40_fu_1152_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_45_fu_1212_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_39_fu_1242_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_38_fu_1236_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_40_fu_1248_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_37_fu_1230_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_46_fu_1260_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_44_fu_1272_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_45_fu_1278_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_44_fu_1272_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_45_fu_1278_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_47_fu_1284_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_46_fu_1296_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_48_fu_1290_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_46_fu_1296_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_47_fu_1314_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_49_fu_1308_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_47_fu_1314_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_48_fu_1332_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_51_fu_1326_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_48_fu_1332_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_52_fu_1338_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_53_fu_1344_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_81_fu_1350_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_49_fu_1356_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_50_fu_1362_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_49_fu_1356_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_50_fu_1362_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_54_fu_1368_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_55_fu_1374_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_56_fu_1380_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_81_fu_1350_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_15_fu_274_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_53_fu_1344_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_50_fu_1320_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_43_fu_1392_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_42_fu_1386_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_14_fu_268_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_80_fu_1302_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_79_fu_1266_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_56_fu_1380_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_46_fu_1410_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_45_fu_1404_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_47_fu_1416_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_44_fu_1398_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_51_fu_1440_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_57_fu_1434_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln103_51_fu_1440_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_58_fu_1446_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_59_fu_1452_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_83_fu_1458_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_61_fu_1470_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_63_fu_1482_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_62_fu_1476_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_63_fu_1482_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_60_fu_1464_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_17_fu_286_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_50_fu_1494_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_49_fu_1488_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_16_fu_280_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln103_59_fu_1452_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_82_fu_1428_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln103_18_fu_292_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_53_fu_1512_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_52_fu_1506_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_54_fu_1518_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_51_fu_1500_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_6_fu_588_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_13_fu_684_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_20_fu_834_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_27_fu_972_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_34_fu_1128_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_41_fu_1254_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_48_fu_1422_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln103_55_fu_1524_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln106_fu_1530_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln107_fu_1536_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln108_fu_1542_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln109_fu_1548_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln110_fu_1554_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln111_fu_1560_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln112_fu_1566_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln113_fu_1572_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln114_fu_1578_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln115_fu_1584_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln116_fu_1590_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln117_fu_1596_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln118_fu_1602_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln119_fu_1608_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln120_fu_1614_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln121_fu_1620_p2 : STD_LOGIC_VECTOR (31 downto 0);

    component IDCT2_IDCT2B8 IS
    port (
        ap_ready : OUT STD_LOGIC;
        in_0_val : IN STD_LOGIC_VECTOR (25 downto 0);
        in_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
        in_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
        in_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
        in_4_val : IN STD_LOGIC_VECTOR (25 downto 0);
        in_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
        in_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
        in_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;


    component IDCT2_mul_32s_7s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component IDCT2_mul_32s_8s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component IDCT2_mul_32s_6s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    call_ret_IDCT2B8_fu_164 : component IDCT2_IDCT2B8
    port map (
        ap_ready => call_ret_IDCT2B8_fu_164_ap_ready,
        in_0_val => in_0_val,
        in_1_val => in_2_val,
        in_2_val => in_4_val,
        in_3_val => in_6_val,
        in_4_val => in_8_val,
        in_5_val => in_10_val,
        in_6_val => in_12_val,
        in_7_val => in_14_val,
        ap_return_0 => call_ret_IDCT2B8_fu_164_ap_return_0,
        ap_return_1 => call_ret_IDCT2B8_fu_164_ap_return_1,
        ap_return_2 => call_ret_IDCT2B8_fu_164_ap_return_2,
        ap_return_3 => call_ret_IDCT2B8_fu_164_ap_return_3,
        ap_return_4 => call_ret_IDCT2B8_fu_164_ap_return_4,
        ap_return_5 => call_ret_IDCT2B8_fu_164_ap_return_5,
        ap_return_6 => call_ret_IDCT2B8_fu_164_ap_return_6,
        ap_return_7 => call_ret_IDCT2B8_fu_164_ap_return_7,
        ap_rst => ap_rst);

    mul_32s_7s_32_1_1_U23 : component IDCT2_mul_32s_7s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 7,
        dout_WIDTH => 32)
    port map (
        din0 => in_7_val,
        din1 => mul_ln103_fu_184_p1,
        dout => mul_ln103_fu_184_p2);

    mul_32s_8s_32_1_1_U24 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_11_val,
        din1 => mul_ln103_1_fu_190_p1,
        dout => mul_ln103_1_fu_190_p2);

    mul_32s_8s_32_1_1_U25 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_13_val,
        din1 => mul_ln103_2_fu_196_p1,
        dout => mul_ln103_2_fu_196_p2);

    mul_32s_6s_32_1_1_U26 : component IDCT2_mul_32s_6s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => in_15_val,
        din1 => mul_ln103_3_fu_202_p1,
        dout => mul_ln103_3_fu_202_p2);

    mul_32s_8s_32_1_1_U27 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_5_val,
        din1 => mul_ln103_4_fu_208_p1,
        dout => mul_ln103_4_fu_208_p2);

    mul_32s_8s_32_1_1_U28 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_7_val,
        din1 => mul_ln103_5_fu_214_p1,
        dout => mul_ln103_5_fu_214_p2);

    mul_32s_6s_32_1_1_U29 : component IDCT2_mul_32s_6s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => in_9_val,
        din1 => mul_ln103_6_fu_220_p1,
        dout => mul_ln103_6_fu_220_p2);

    mul_32s_7s_32_1_1_U30 : component IDCT2_mul_32s_7s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 7,
        dout_WIDTH => 32)
    port map (
        din0 => in_3_val,
        din1 => mul_ln103_7_fu_226_p1,
        dout => mul_ln103_7_fu_226_p2);

    mul_32s_8s_32_1_1_U31 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_5_val,
        din1 => mul_ln103_8_fu_232_p1,
        dout => mul_ln103_8_fu_232_p2);

    mul_32s_7s_32_1_1_U32 : component IDCT2_mul_32s_7s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 7,
        dout_WIDTH => 32)
    port map (
        din0 => in_15_val,
        din1 => mul_ln103_9_fu_238_p1,
        dout => mul_ln103_9_fu_238_p2);

    mul_32s_6s_32_1_1_U33 : component IDCT2_mul_32s_6s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => in_5_val,
        din1 => mul_ln103_10_fu_244_p1,
        dout => mul_ln103_10_fu_244_p2);

    mul_32s_8s_32_1_1_U34 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_11_val,
        din1 => mul_ln103_11_fu_250_p1,
        dout => mul_ln103_11_fu_250_p2);

    mul_32s_8s_32_1_1_U35 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_3_val,
        din1 => mul_ln103_12_fu_256_p1,
        dout => mul_ln103_12_fu_256_p2);

    mul_32s_8s_32_1_1_U36 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_9_val,
        din1 => mul_ln103_13_fu_262_p1,
        dout => mul_ln103_13_fu_262_p2);

    mul_32s_8s_32_1_1_U37 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_3_val,
        din1 => mul_ln103_14_fu_268_p1,
        dout => mul_ln103_14_fu_268_p2);

    mul_32s_7s_32_1_1_U38 : component IDCT2_mul_32s_7s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 7,
        dout_WIDTH => 32)
    port map (
        din0 => in_13_val,
        din1 => mul_ln103_15_fu_274_p1,
        dout => mul_ln103_15_fu_274_p2);

    mul_32s_6s_32_1_1_U39 : component IDCT2_mul_32s_6s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => in_3_val,
        din1 => mul_ln103_16_fu_280_p1,
        dout => mul_ln103_16_fu_280_p2);

    mul_32s_7s_32_1_1_U40 : component IDCT2_mul_32s_7s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 7,
        dout_WIDTH => 32)
    port map (
        din0 => in_7_val,
        din1 => mul_ln103_17_fu_286_p1,
        dout => mul_ln103_17_fu_286_p2);

    mul_32s_8s_32_1_1_U41 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_15_val,
        din1 => mul_ln103_18_fu_292_p1,
        dout => mul_ln103_18_fu_292_p2);




    add_ln103_10_fu_666_p2 <= std_logic_vector(unsigned(add_ln103_62_fu_612_p2) + unsigned(add_ln103_63_fu_624_p2));
    add_ln103_11_fu_672_p2 <= std_logic_vector(unsigned(sub_ln103_11_fu_594_p2) + unsigned(mul_ln103_3_fu_202_p2));
    add_ln103_12_fu_678_p2 <= std_logic_vector(unsigned(add_ln103_11_fu_672_p2) + unsigned(add_ln103_10_fu_666_p2));
    add_ln103_13_fu_684_p2 <= std_logic_vector(unsigned(add_ln103_12_fu_678_p2) + unsigned(add_ln103_9_fu_660_p2));
    add_ln103_14_fu_798_p2 <= std_logic_vector(unsigned(add_ln103_66_fu_726_p2) + unsigned(add_ln103_67_fu_756_p2));
    add_ln103_15_fu_804_p2 <= std_logic_vector(unsigned(mul_ln103_6_fu_220_p2) + unsigned(mul_ln103_5_fu_214_p2));
    add_ln103_16_fu_810_p2 <= std_logic_vector(unsigned(add_ln103_15_fu_804_p2) + unsigned(add_ln103_14_fu_798_p2));
    add_ln103_17_fu_816_p2 <= std_logic_vector(unsigned(add_ln103_65_fu_708_p2) + unsigned(mul_ln103_4_fu_208_p2));
    add_ln103_18_fu_822_p2 <= std_logic_vector(unsigned(add_ln103_64_fu_702_p2) + unsigned(sub_ln103_20_fu_792_p2));
    add_ln103_19_fu_828_p2 <= std_logic_vector(unsigned(add_ln103_18_fu_822_p2) + unsigned(add_ln103_17_fu_816_p2));
    add_ln103_1_fu_558_p2 <= std_logic_vector(unsigned(add_ln103_59_fu_474_p2) + unsigned(sub_ln103_5_fu_450_p2));
    add_ln103_20_fu_834_p2 <= std_logic_vector(unsigned(add_ln103_19_fu_828_p2) + unsigned(add_ln103_16_fu_810_p2));
    add_ln103_21_fu_936_p2 <= std_logic_vector(unsigned(add_ln103_71_fu_906_p2) + unsigned(sub_ln103_26_fu_930_p2));
    add_ln103_22_fu_942_p2 <= std_logic_vector(unsigned(add_ln103_70_fu_888_p2) + unsigned(add_ln103_69_fu_852_p2));
    add_ln103_23_fu_948_p2 <= std_logic_vector(unsigned(add_ln103_22_fu_942_p2) + unsigned(add_ln103_21_fu_936_p2));
    add_ln103_24_fu_954_p2 <= std_logic_vector(unsigned(mul_ln103_7_fu_226_p2) + unsigned(mul_ln103_8_fu_232_p2));
    add_ln103_25_fu_960_p2 <= std_logic_vector(unsigned(sub_ln103_21_fu_846_p2) + unsigned(mul_ln103_9_fu_238_p2));
    add_ln103_26_fu_966_p2 <= std_logic_vector(unsigned(add_ln103_25_fu_960_p2) + unsigned(add_ln103_24_fu_954_p2));
    add_ln103_27_fu_972_p2 <= std_logic_vector(unsigned(add_ln103_26_fu_966_p2) + unsigned(add_ln103_23_fu_948_p2));
    add_ln103_28_fu_1092_p2 <= std_logic_vector(unsigned(mul_ln103_11_fu_250_p2) + unsigned(sub_ln103_36_fu_1068_p2));
    add_ln103_29_fu_1098_p2 <= std_logic_vector(unsigned(sub_ln103_33_fu_1044_p2) + unsigned(add_ln103_73_fu_1032_p2));
    add_ln103_2_fu_564_p2 <= std_logic_vector(unsigned(add_ln103_1_fu_558_p2) + unsigned(add_ln103_fu_552_p2));
    add_ln103_30_fu_1104_p2 <= std_logic_vector(unsigned(add_ln103_29_fu_1098_p2) + unsigned(add_ln103_28_fu_1092_p2));
    add_ln103_31_fu_1110_p2 <= std_logic_vector(unsigned(sub_ln103_29_fu_1002_p2) + unsigned(mul_ln103_10_fu_244_p2));
    add_ln103_32_fu_1116_p2 <= std_logic_vector(unsigned(add_ln103_72_fu_984_p2) + unsigned(sub_ln103_37_fu_1086_p2));
    add_ln103_33_fu_1122_p2 <= std_logic_vector(unsigned(add_ln103_32_fu_1116_p2) + unsigned(add_ln103_31_fu_1110_p2));
    add_ln103_34_fu_1128_p2 <= std_logic_vector(unsigned(add_ln103_33_fu_1122_p2) + unsigned(add_ln103_30_fu_1104_p2));
    add_ln103_35_fu_1218_p2 <= std_logic_vector(unsigned(sub_ln103_43_fu_1194_p2) + unsigned(add_ln103_78_fu_1200_p2));
    add_ln103_36_fu_1224_p2 <= std_logic_vector(unsigned(mul_ln103_13_fu_262_p2) + unsigned(add_ln103_76_fu_1176_p2));
    add_ln103_37_fu_1230_p2 <= std_logic_vector(unsigned(add_ln103_36_fu_1224_p2) + unsigned(add_ln103_35_fu_1218_p2));
    add_ln103_38_fu_1236_p2 <= std_logic_vector(unsigned(mul_ln103_12_fu_256_p2) + unsigned(add_ln103_75_fu_1164_p2));
    add_ln103_39_fu_1242_p2 <= std_logic_vector(unsigned(sub_ln103_40_fu_1152_p2) + unsigned(sub_ln103_45_fu_1212_p2));
    add_ln103_3_fu_570_p2 <= std_logic_vector(unsigned(sub_ln103_4_fu_402_p2) + unsigned(add_ln103_57_fu_420_p2));
    add_ln103_40_fu_1248_p2 <= std_logic_vector(unsigned(add_ln103_39_fu_1242_p2) + unsigned(add_ln103_38_fu_1236_p2));
    add_ln103_41_fu_1254_p2 <= std_logic_vector(unsigned(add_ln103_40_fu_1248_p2) + unsigned(add_ln103_37_fu_1230_p2));
    add_ln103_42_fu_1386_p2 <= std_logic_vector(unsigned(add_ln103_81_fu_1350_p2) + unsigned(mul_ln103_15_fu_274_p2));
    add_ln103_43_fu_1392_p2 <= std_logic_vector(unsigned(sub_ln103_53_fu_1344_p2) + unsigned(sub_ln103_50_fu_1320_p2));
    add_ln103_44_fu_1398_p2 <= std_logic_vector(unsigned(add_ln103_43_fu_1392_p2) + unsigned(add_ln103_42_fu_1386_p2));
    add_ln103_45_fu_1404_p2 <= std_logic_vector(unsigned(mul_ln103_14_fu_268_p2) + unsigned(add_ln103_80_fu_1302_p2));
    add_ln103_46_fu_1410_p2 <= std_logic_vector(unsigned(add_ln103_79_fu_1266_p2) + unsigned(sub_ln103_56_fu_1380_p2));
    add_ln103_47_fu_1416_p2 <= std_logic_vector(unsigned(add_ln103_46_fu_1410_p2) + unsigned(add_ln103_45_fu_1404_p2));
    add_ln103_48_fu_1422_p2 <= std_logic_vector(unsigned(add_ln103_47_fu_1416_p2) + unsigned(add_ln103_44_fu_1398_p2));
    add_ln103_49_fu_1488_p2 <= std_logic_vector(unsigned(sub_ln103_62_fu_1476_p2) + unsigned(sub_ln103_63_fu_1482_p2));
    add_ln103_4_fu_576_p2 <= std_logic_vector(unsigned(add_ln103_56_fu_366_p2) + unsigned(add_ln103_61_fu_546_p2));
    add_ln103_50_fu_1494_p2 <= std_logic_vector(unsigned(sub_ln103_60_fu_1464_p2) + unsigned(mul_ln103_17_fu_286_p2));
    add_ln103_51_fu_1500_p2 <= std_logic_vector(unsigned(add_ln103_50_fu_1494_p2) + unsigned(add_ln103_49_fu_1488_p2));
    add_ln103_52_fu_1506_p2 <= std_logic_vector(unsigned(mul_ln103_16_fu_280_p2) + unsigned(sub_ln103_59_fu_1452_p2));
    add_ln103_53_fu_1512_p2 <= std_logic_vector(unsigned(add_ln103_82_fu_1428_p2) + unsigned(mul_ln103_18_fu_292_p2));
    add_ln103_54_fu_1518_p2 <= std_logic_vector(unsigned(add_ln103_53_fu_1512_p2) + unsigned(add_ln103_52_fu_1506_p2));
    add_ln103_55_fu_1524_p2 <= std_logic_vector(unsigned(add_ln103_54_fu_1518_p2) + unsigned(add_ln103_51_fu_1500_p2));
    add_ln103_56_fu_366_p2 <= std_logic_vector(unsigned(sub_ln103_1_fu_354_p2) + unsigned(shl_ln103_3_fu_360_p2));
    add_ln103_57_fu_420_p2 <= std_logic_vector(unsigned(shl_ln103_7_fu_408_p2) + unsigned(shl_ln103_8_fu_414_p2));
    add_ln103_58_fu_438_p2 <= std_logic_vector(unsigned(shl_ln103_9_fu_426_p2) + unsigned(shl_ln103_10_fu_432_p2));
    add_ln103_59_fu_474_p1 <= in_9_val;
    add_ln103_59_fu_474_p2 <= std_logic_vector(unsigned(sub_ln103_6_fu_468_p2) + unsigned(add_ln103_59_fu_474_p1));
    add_ln103_5_fu_582_p2 <= std_logic_vector(unsigned(add_ln103_4_fu_576_p2) + unsigned(add_ln103_3_fu_570_p2));
    add_ln103_60_fu_534_p1 <= in_13_val;
    add_ln103_60_fu_534_p2 <= std_logic_vector(unsigned(sub_ln103_10_fu_528_p2) + unsigned(add_ln103_60_fu_534_p1));
    add_ln103_61_fu_546_p1 <= in_15_val;
    add_ln103_61_fu_546_p2 <= std_logic_vector(unsigned(shl_ln103_19_fu_540_p2) + unsigned(add_ln103_61_fu_546_p1));
    add_ln103_62_fu_612_p1 <= in_3_val;
    add_ln103_62_fu_612_p2 <= std_logic_vector(unsigned(sub_ln103_12_fu_606_p2) + unsigned(add_ln103_62_fu_612_p1));
    add_ln103_63_fu_624_p1 <= in_5_val;
    add_ln103_63_fu_624_p2 <= std_logic_vector(unsigned(shl_ln103_21_fu_618_p2) + unsigned(add_ln103_63_fu_624_p1));
    add_ln103_64_fu_702_p2 <= std_logic_vector(unsigned(shl_ln103_23_fu_690_p2) + unsigned(shl_ln103_24_fu_696_p2));
    add_ln103_65_fu_708_p1 <= in_3_val;
    add_ln103_65_fu_708_p2 <= std_logic_vector(unsigned(shl_ln103_6_fu_390_p2) + unsigned(add_ln103_65_fu_708_p1));
    add_ln103_66_fu_726_p1 <= in_11_val;
    add_ln103_66_fu_726_p2 <= std_logic_vector(unsigned(sub_ln103_15_fu_720_p2) + unsigned(add_ln103_66_fu_726_p1));
    add_ln103_67_fu_756_p2 <= std_logic_vector(unsigned(sub_ln103_17_fu_744_p2) + unsigned(shl_ln103_27_fu_750_p2));
    add_ln103_68_fu_840_p2 <= std_logic_vector(unsigned(shl_ln103_23_fu_690_p2) + unsigned(shl_ln103_2_fu_348_p2));
    add_ln103_69_fu_852_p1 <= in_7_val;
    add_ln103_69_fu_852_p2 <= std_logic_vector(unsigned(shl_ln103_10_fu_432_p2) + unsigned(add_ln103_69_fu_852_p1));
    add_ln103_6_fu_588_p2 <= std_logic_vector(unsigned(add_ln103_5_fu_582_p2) + unsigned(add_ln103_2_fu_564_p2));
    add_ln103_70_fu_888_p2 <= std_logic_vector(unsigned(sub_ln103_23_fu_876_p2) + unsigned(shl_ln103_33_fu_882_p2));
    add_ln103_71_fu_906_p1 <= in_11_val;
    add_ln103_71_fu_906_p2 <= std_logic_vector(unsigned(sub_ln103_24_fu_900_p2) + unsigned(add_ln103_71_fu_906_p1));
    add_ln103_72_fu_984_p2 <= std_logic_vector(unsigned(sub_ln103_27_fu_978_p2) + unsigned(in_1_val));
    add_ln103_73_fu_1032_p2 <= std_logic_vector(unsigned(sub_ln103_31_fu_1026_p2) + unsigned(shl_ln103_11_fu_444_p2));
    add_ln103_74_fu_1074_p2 <= std_logic_vector(unsigned(shl_ln103_28_fu_762_p2) + unsigned(shl_ln103_19_fu_540_p2));
    add_ln103_75_fu_1164_p1 <= in_5_val;
    add_ln103_75_fu_1164_p2 <= std_logic_vector(unsigned(sub_ln103_41_fu_1158_p2) + unsigned(add_ln103_75_fu_1164_p1));
    add_ln103_76_fu_1176_p1 <= in_7_val;
    add_ln103_76_fu_1176_p2 <= std_logic_vector(unsigned(sub_ln103_42_fu_1170_p2) + unsigned(add_ln103_76_fu_1176_p1));
    add_ln103_77_fu_1182_p2 <= std_logic_vector(unsigned(shl_ln103_14_fu_480_p2) + unsigned(shl_ln103_25_fu_714_p2));
    add_ln103_78_fu_1200_p1 <= in_13_val;
    add_ln103_78_fu_1200_p2 <= std_logic_vector(unsigned(shl_ln103_18_fu_522_p2) + unsigned(add_ln103_78_fu_1200_p1));
    add_ln103_79_fu_1266_p2 <= std_logic_vector(unsigned(sub_ln103_46_fu_1260_p2) + unsigned(in_1_val));
    add_ln103_7_fu_648_p2 <= std_logic_vector(unsigned(mul_ln103_1_fu_190_p2) + unsigned(mul_ln103_2_fu_196_p2));
    add_ln103_80_fu_1302_p2 <= std_logic_vector(unsigned(sub_ln103_48_fu_1290_p2) + unsigned(shl_ln103_46_fu_1296_p2));
    add_ln103_81_fu_1350_p1 <= in_11_val;
    add_ln103_81_fu_1350_p2 <= std_logic_vector(unsigned(shl_ln103_25_fu_714_p2) + unsigned(add_ln103_81_fu_1350_p1));
    add_ln103_82_fu_1428_p2 <= std_logic_vector(unsigned(shl_ln103_2_fu_348_p2) + unsigned(in_1_val));
    add_ln103_83_fu_1458_p2 <= std_logic_vector(unsigned(shl_ln103_12_fu_456_p2) + unsigned(shl_ln103_13_fu_462_p2));
    add_ln103_8_fu_654_p2 <= std_logic_vector(unsigned(sub_ln103_14_fu_642_p2) + unsigned(mul_ln103_fu_184_p2));
    add_ln103_9_fu_660_p2 <= std_logic_vector(unsigned(add_ln103_8_fu_654_p2) + unsigned(add_ln103_7_fu_648_p2));
    add_ln103_fu_552_p2 <= std_logic_vector(unsigned(sub_ln103_9_fu_510_p2) + unsigned(add_ln103_60_fu_534_p2));
    add_ln106_fu_1530_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_0) + unsigned(add_ln103_6_fu_588_p2));
    add_ln107_fu_1536_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_1) + unsigned(add_ln103_13_fu_684_p2));
    add_ln108_fu_1542_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_2) + unsigned(add_ln103_20_fu_834_p2));
    add_ln109_fu_1548_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_3) + unsigned(add_ln103_27_fu_972_p2));
    add_ln110_fu_1554_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_4) + unsigned(add_ln103_34_fu_1128_p2));
    add_ln111_fu_1560_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_5) + unsigned(add_ln103_41_fu_1254_p2));
    add_ln112_fu_1566_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_6) + unsigned(add_ln103_48_fu_1422_p2));
    add_ln113_fu_1572_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_7) + unsigned(add_ln103_55_fu_1524_p2));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln106_fu_1530_p2;
    ap_return_1 <= add_ln107_fu_1536_p2;
    ap_return_10 <= sub_ln116_fu_1590_p2;
    ap_return_11 <= sub_ln117_fu_1596_p2;
    ap_return_12 <= sub_ln118_fu_1602_p2;
    ap_return_13 <= sub_ln119_fu_1608_p2;
    ap_return_14 <= sub_ln120_fu_1614_p2;
    ap_return_15 <= sub_ln121_fu_1620_p2;
    ap_return_2 <= add_ln108_fu_1542_p2;
    ap_return_3 <= add_ln109_fu_1548_p2;
    ap_return_4 <= add_ln110_fu_1554_p2;
    ap_return_5 <= add_ln111_fu_1560_p2;
    ap_return_6 <= add_ln112_fu_1566_p2;
    ap_return_7 <= add_ln113_fu_1572_p2;
    ap_return_8 <= sub_ln114_fu_1578_p2;
    ap_return_9 <= sub_ln115_fu_1584_p2;
    mul_ln103_10_fu_244_p1 <= ap_const_lv32_FFFFFFE7(6 - 1 downto 0);
    mul_ln103_11_fu_250_p1 <= ap_const_lv32_FFFFFFA9(8 - 1 downto 0);
    mul_ln103_12_fu_256_p1 <= ap_const_lv32_FFFFFFA6(8 - 1 downto 0);
    mul_ln103_13_fu_262_p1 <= ap_const_lv32_FFFFFFA9(8 - 1 downto 0);
    mul_ln103_14_fu_268_p1 <= ap_const_lv32_FFFFFFBA(8 - 1 downto 0);
    mul_ln103_15_fu_274_p1 <= ap_const_lv32_FFFFFFC7(7 - 1 downto 0);
    mul_ln103_16_fu_280_p1 <= ap_const_lv32_FFFFFFE7(6 - 1 downto 0);
    mul_ln103_17_fu_286_p1 <= ap_const_lv32_FFFFFFC7(7 - 1 downto 0);
    mul_ln103_18_fu_292_p1 <= ap_const_lv32_FFFFFFA6(8 - 1 downto 0);
    mul_ln103_1_fu_190_p1 <= ap_const_lv32_FFFFFFA6(8 - 1 downto 0);
    mul_ln103_2_fu_196_p1 <= ap_const_lv32_FFFFFFBA(8 - 1 downto 0);
    mul_ln103_3_fu_202_p1 <= ap_const_lv32_FFFFFFE7(6 - 1 downto 0);
    mul_ln103_4_fu_208_p1 <= ap_const_lv32_FFFFFFBA(8 - 1 downto 0);
    mul_ln103_5_fu_214_p1 <= ap_const_lv32_FFFFFFA9(8 - 1 downto 0);
    mul_ln103_6_fu_220_p1 <= ap_const_lv32_FFFFFFE7(6 - 1 downto 0);
    mul_ln103_7_fu_226_p1 <= ap_const_lv32_FFFFFFD5(7 - 1 downto 0);
    mul_ln103_8_fu_232_p1 <= ap_const_lv32_FFFFFFA9(8 - 1 downto 0);
    mul_ln103_9_fu_238_p1 <= ap_const_lv32_FFFFFFC7(7 - 1 downto 0);
    mul_ln103_fu_184_p1 <= ap_const_lv32_FFFFFFD5(7 - 1 downto 0);
    shl_ln103_10_fu_432_p0 <= in_7_val;
    shl_ln103_10_fu_432_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_10_fu_432_p0),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    shl_ln103_11_fu_444_p0 <= in_7_val;
    shl_ln103_11_fu_444_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_11_fu_444_p0),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln103_12_fu_456_p0 <= in_9_val;
    shl_ln103_12_fu_456_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_12_fu_456_p0),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln103_13_fu_462_p0 <= in_9_val;
    shl_ln103_13_fu_462_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_13_fu_462_p0),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    shl_ln103_14_fu_480_p0 <= in_11_val;
    shl_ln103_14_fu_480_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_14_fu_480_p0),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln103_15_fu_486_p0 <= in_11_val;
    shl_ln103_15_fu_486_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_15_fu_486_p0),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln103_16_fu_498_p0 <= in_11_val;
    shl_ln103_16_fu_498_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_16_fu_498_p0),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln103_17_fu_516_p0 <= in_13_val;
    shl_ln103_17_fu_516_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_17_fu_516_p0),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln103_18_fu_522_p0 <= in_13_val;
    shl_ln103_18_fu_522_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_18_fu_522_p0),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    shl_ln103_19_fu_540_p0 <= in_15_val;
    shl_ln103_19_fu_540_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_19_fu_540_p0),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    shl_ln103_1_fu_336_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln103_20_fu_600_p0 <= in_3_val;
    shl_ln103_20_fu_600_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_20_fu_600_p0),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln103_21_fu_618_p0 <= in_5_val;
    shl_ln103_21_fu_618_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_21_fu_618_p0),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    shl_ln103_22_fu_636_p0 <= in_9_val;
    shl_ln103_22_fu_636_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_22_fu_636_p0),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln103_23_fu_690_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln103_24_fu_696_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln103_25_fu_714_p0 <= in_11_val;
    shl_ln103_25_fu_714_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_25_fu_714_p0),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    shl_ln103_26_fu_732_p0 <= in_13_val;
    shl_ln103_26_fu_732_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_26_fu_732_p0),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    shl_ln103_27_fu_750_p0 <= in_13_val;
    shl_ln103_27_fu_750_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_27_fu_750_p0),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln103_28_fu_762_p0 <= in_15_val;
    shl_ln103_28_fu_762_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_28_fu_762_p0),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln103_29_fu_768_p0 <= in_15_val;
    shl_ln103_29_fu_768_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_29_fu_768_p0),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln103_2_fu_348_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    shl_ln103_30_fu_780_p0 <= in_15_val;
    shl_ln103_30_fu_780_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_30_fu_780_p0),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln103_31_fu_858_p0 <= in_9_val;
    shl_ln103_31_fu_858_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_31_fu_858_p0),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    shl_ln103_32_fu_864_p0 <= in_9_val;
    shl_ln103_32_fu_864_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_32_fu_864_p0),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln103_33_fu_882_p0 <= in_9_val;
    shl_ln103_33_fu_882_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_33_fu_882_p0),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln103_34_fu_894_p0 <= in_11_val;
    shl_ln103_34_fu_894_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_34_fu_894_p0),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln103_35_fu_912_p0 <= in_13_val;
    shl_ln103_35_fu_912_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_35_fu_912_p0),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln103_36_fu_924_p0 <= in_13_val;
    shl_ln103_36_fu_924_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_36_fu_924_p0),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln103_37_fu_996_p0 <= in_3_val;
    shl_ln103_37_fu_996_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_37_fu_996_p0),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln103_38_fu_1008_p0 <= in_7_val;
    shl_ln103_38_fu_1008_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_38_fu_1008_p0),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    shl_ln103_39_fu_1014_p0 <= in_7_val;
    shl_ln103_39_fu_1014_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_39_fu_1014_p0),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln103_3_fu_360_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln103_40_fu_1056_p0 <= in_13_val;
    shl_ln103_40_fu_1056_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_40_fu_1056_p0),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln103_41_fu_1080_p0 <= in_15_val;
    shl_ln103_41_fu_1080_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_41_fu_1080_p0),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln103_42_fu_1140_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln103_43_fu_1188_p0 <= in_11_val;
    shl_ln103_43_fu_1188_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_43_fu_1188_p0),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln103_44_fu_1272_p0 <= in_5_val;
    shl_ln103_44_fu_1272_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_44_fu_1272_p0),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    shl_ln103_45_fu_1278_p0 <= in_5_val;
    shl_ln103_45_fu_1278_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_45_fu_1278_p0),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln103_46_fu_1296_p0 <= in_5_val;
    shl_ln103_46_fu_1296_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_46_fu_1296_p0),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln103_47_fu_1314_p0 <= in_7_val;
    shl_ln103_47_fu_1314_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_47_fu_1314_p0),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln103_48_fu_1332_p0 <= in_9_val;
    shl_ln103_48_fu_1332_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_48_fu_1332_p0),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln103_49_fu_1356_p0 <= in_15_val;
    shl_ln103_49_fu_1356_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_49_fu_1356_p0),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    shl_ln103_4_fu_372_p0 <= in_3_val;
    shl_ln103_4_fu_372_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_4_fu_372_p0),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    shl_ln103_50_fu_1362_p0 <= in_15_val;
    shl_ln103_50_fu_1362_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_50_fu_1362_p0),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln103_51_fu_1440_p0 <= in_5_val;
    shl_ln103_51_fu_1440_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_51_fu_1440_p0),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln103_5_fu_378_p0 <= in_3_val;
    shl_ln103_5_fu_378_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_5_fu_378_p0),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln103_6_fu_390_p0 <= in_3_val;
    shl_ln103_6_fu_390_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_6_fu_390_p0),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    shl_ln103_7_fu_408_p0 <= in_5_val;
    shl_ln103_7_fu_408_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_7_fu_408_p0),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln103_8_fu_414_p0 <= in_5_val;
    shl_ln103_8_fu_414_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_8_fu_414_p0),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln103_9_fu_426_p0 <= in_7_val;
    shl_ln103_9_fu_426_p2 <= std_logic_vector(shift_left(unsigned(shl_ln103_9_fu_426_p0),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln103_fu_330_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    sub_ln103_10_fu_528_p2 <= std_logic_vector(unsigned(shl_ln103_17_fu_516_p2) - unsigned(shl_ln103_18_fu_522_p2));
    sub_ln103_11_fu_594_p2 <= std_logic_vector(unsigned(sub_ln103_1_fu_354_p2) - unsigned(in_1_val));
    sub_ln103_12_fu_606_p2 <= std_logic_vector(unsigned(shl_ln103_20_fu_600_p2) - unsigned(shl_ln103_6_fu_390_p2));
    sub_ln103_13_fu_630_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln103_12_fu_456_p2));
    sub_ln103_14_fu_642_p2 <= std_logic_vector(unsigned(sub_ln103_13_fu_630_p2) - unsigned(shl_ln103_22_fu_636_p2));
    sub_ln103_15_fu_720_p2 <= std_logic_vector(unsigned(shl_ln103_14_fu_480_p2) - unsigned(shl_ln103_25_fu_714_p2));
    sub_ln103_16_fu_738_p2 <= std_logic_vector(unsigned(shl_ln103_26_fu_732_p2) - unsigned(shl_ln103_17_fu_516_p2));
    sub_ln103_17_fu_744_p2 <= std_logic_vector(unsigned(sub_ln103_16_fu_738_p2) - unsigned(shl_ln103_18_fu_522_p2));
    sub_ln103_18_fu_774_p2 <= std_logic_vector(unsigned(shl_ln103_28_fu_762_p2) - unsigned(shl_ln103_29_fu_768_p2));
    sub_ln103_19_fu_786_p2 <= std_logic_vector(unsigned(sub_ln103_18_fu_774_p2) - unsigned(shl_ln103_30_fu_780_p2));
    sub_ln103_1_fu_354_p2 <= std_logic_vector(unsigned(sub_ln103_fu_342_p2) - unsigned(shl_ln103_2_fu_348_p2));
    sub_ln103_20_fu_792_p1 <= in_15_val;
    sub_ln103_20_fu_792_p2 <= std_logic_vector(unsigned(sub_ln103_19_fu_786_p2) - unsigned(sub_ln103_20_fu_792_p1));
    sub_ln103_21_fu_846_p2 <= std_logic_vector(unsigned(add_ln103_68_fu_840_p2) - unsigned(shl_ln103_3_fu_360_p2));
    sub_ln103_22_fu_870_p2 <= std_logic_vector(unsigned(shl_ln103_31_fu_858_p2) - unsigned(shl_ln103_32_fu_864_p2));
    sub_ln103_23_fu_876_p2 <= std_logic_vector(unsigned(sub_ln103_22_fu_870_p2) - unsigned(shl_ln103_13_fu_462_p2));
    sub_ln103_24_fu_900_p2 <= std_logic_vector(unsigned(shl_ln103_34_fu_894_p2) - unsigned(shl_ln103_25_fu_714_p2));
    sub_ln103_25_fu_918_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln103_35_fu_912_p2));
    sub_ln103_26_fu_930_p2 <= std_logic_vector(unsigned(sub_ln103_25_fu_918_p2) - unsigned(shl_ln103_36_fu_924_p2));
    sub_ln103_27_fu_978_p2 <= std_logic_vector(unsigned(shl_ln103_23_fu_690_p2) - unsigned(shl_ln103_2_fu_348_p2));
    sub_ln103_28_fu_990_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln103_20_fu_600_p2));
    sub_ln103_29_fu_1002_p2 <= std_logic_vector(unsigned(sub_ln103_28_fu_990_p2) - unsigned(shl_ln103_37_fu_996_p2));
    sub_ln103_2_fu_384_p2 <= std_logic_vector(unsigned(shl_ln103_4_fu_372_p2) - unsigned(shl_ln103_5_fu_378_p2));
    sub_ln103_30_fu_1020_p2 <= std_logic_vector(unsigned(shl_ln103_38_fu_1008_p2) - unsigned(shl_ln103_39_fu_1014_p2));
    sub_ln103_31_fu_1026_p2 <= std_logic_vector(unsigned(sub_ln103_30_fu_1020_p2) - unsigned(shl_ln103_10_fu_432_p2));
    sub_ln103_32_fu_1038_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln103_13_fu_462_p2));
    sub_ln103_33_fu_1044_p1 <= in_9_val;
    sub_ln103_33_fu_1044_p2 <= std_logic_vector(unsigned(sub_ln103_32_fu_1038_p2) - unsigned(sub_ln103_33_fu_1044_p1));
    sub_ln103_34_fu_1050_p2 <= std_logic_vector(unsigned(shl_ln103_35_fu_912_p2) - unsigned(shl_ln103_36_fu_924_p2));
    sub_ln103_35_fu_1062_p2 <= std_logic_vector(unsigned(sub_ln103_34_fu_1050_p2) - unsigned(shl_ln103_40_fu_1056_p2));
    sub_ln103_36_fu_1068_p1 <= in_13_val;
    sub_ln103_36_fu_1068_p2 <= std_logic_vector(unsigned(sub_ln103_35_fu_1062_p2) - unsigned(sub_ln103_36_fu_1068_p1));
    sub_ln103_37_fu_1086_p2 <= std_logic_vector(unsigned(add_ln103_74_fu_1074_p2) - unsigned(shl_ln103_41_fu_1080_p2));
    sub_ln103_38_fu_1134_p2 <= std_logic_vector(unsigned(shl_ln103_23_fu_690_p2) - unsigned(shl_ln103_24_fu_696_p2));
    sub_ln103_39_fu_1146_p2 <= std_logic_vector(unsigned(sub_ln103_38_fu_1134_p2) - unsigned(shl_ln103_42_fu_1140_p2));
    sub_ln103_3_fu_396_p2 <= std_logic_vector(unsigned(sub_ln103_2_fu_384_p2) - unsigned(shl_ln103_6_fu_390_p2));
    sub_ln103_40_fu_1152_p2 <= std_logic_vector(unsigned(sub_ln103_39_fu_1146_p2) - unsigned(in_1_val));
    sub_ln103_41_fu_1158_p2 <= std_logic_vector(unsigned(shl_ln103_7_fu_408_p2) - unsigned(shl_ln103_21_fu_618_p2));
    sub_ln103_42_fu_1170_p2 <= std_logic_vector(unsigned(shl_ln103_39_fu_1014_p2) - unsigned(shl_ln103_10_fu_432_p2));
    sub_ln103_43_fu_1194_p2 <= std_logic_vector(unsigned(add_ln103_77_fu_1182_p2) - unsigned(shl_ln103_43_fu_1188_p2));
    sub_ln103_44_fu_1206_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln103_28_fu_762_p2));
    sub_ln103_45_fu_1212_p2 <= std_logic_vector(unsigned(sub_ln103_44_fu_1206_p2) - unsigned(shl_ln103_29_fu_768_p2));
    sub_ln103_46_fu_1260_p2 <= std_logic_vector(unsigned(shl_ln103_1_fu_336_p2) - unsigned(shl_ln103_2_fu_348_p2));
    sub_ln103_47_fu_1284_p2 <= std_logic_vector(unsigned(shl_ln103_44_fu_1272_p2) - unsigned(shl_ln103_45_fu_1278_p2));
    sub_ln103_48_fu_1290_p2 <= std_logic_vector(unsigned(sub_ln103_47_fu_1284_p2) - unsigned(shl_ln103_21_fu_618_p2));
    sub_ln103_49_fu_1308_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln103_9_fu_426_p2));
    sub_ln103_4_fu_402_p1 <= in_3_val;
    sub_ln103_4_fu_402_p2 <= std_logic_vector(unsigned(sub_ln103_3_fu_396_p2) - unsigned(sub_ln103_4_fu_402_p1));
    sub_ln103_50_fu_1320_p2 <= std_logic_vector(unsigned(sub_ln103_49_fu_1308_p2) - unsigned(shl_ln103_47_fu_1314_p2));
    sub_ln103_51_fu_1326_p2 <= std_logic_vector(unsigned(shl_ln103_12_fu_456_p2) - unsigned(shl_ln103_22_fu_636_p2));
    sub_ln103_52_fu_1338_p2 <= std_logic_vector(unsigned(sub_ln103_51_fu_1326_p2) - unsigned(shl_ln103_48_fu_1332_p2));
    sub_ln103_53_fu_1344_p1 <= in_9_val;
    sub_ln103_53_fu_1344_p2 <= std_logic_vector(unsigned(sub_ln103_52_fu_1338_p2) - unsigned(sub_ln103_53_fu_1344_p1));
    sub_ln103_54_fu_1368_p2 <= std_logic_vector(unsigned(shl_ln103_49_fu_1356_p2) - unsigned(shl_ln103_50_fu_1362_p2));
    sub_ln103_55_fu_1374_p2 <= std_logic_vector(unsigned(sub_ln103_54_fu_1368_p2) - unsigned(shl_ln103_19_fu_540_p2));
    sub_ln103_56_fu_1380_p1 <= in_15_val;
    sub_ln103_56_fu_1380_p2 <= std_logic_vector(unsigned(sub_ln103_55_fu_1374_p2) - unsigned(sub_ln103_56_fu_1380_p1));
    sub_ln103_57_fu_1434_p2 <= std_logic_vector(unsigned(shl_ln103_7_fu_408_p2) - unsigned(shl_ln103_8_fu_414_p2));
    sub_ln103_58_fu_1446_p2 <= std_logic_vector(unsigned(sub_ln103_57_fu_1434_p2) - unsigned(shl_ln103_51_fu_1440_p2));
    sub_ln103_59_fu_1452_p1 <= in_5_val;
    sub_ln103_59_fu_1452_p2 <= std_logic_vector(unsigned(sub_ln103_58_fu_1446_p2) - unsigned(sub_ln103_59_fu_1452_p1));
    sub_ln103_5_fu_450_p2 <= std_logic_vector(unsigned(add_ln103_58_fu_438_p2) - unsigned(shl_ln103_11_fu_444_p2));
    sub_ln103_60_fu_1464_p2 <= std_logic_vector(unsigned(add_ln103_83_fu_1458_p2) - unsigned(shl_ln103_33_fu_882_p2));
    sub_ln103_61_fu_1470_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln103_14_fu_480_p2));
    sub_ln103_62_fu_1476_p2 <= std_logic_vector(unsigned(sub_ln103_61_fu_1470_p2) - unsigned(shl_ln103_15_fu_486_p2));
    sub_ln103_63_fu_1482_p1 <= in_13_val;
    sub_ln103_63_fu_1482_p2 <= std_logic_vector(unsigned(sub_ln103_17_fu_744_p2) - unsigned(sub_ln103_63_fu_1482_p1));
    sub_ln103_6_fu_468_p2 <= std_logic_vector(unsigned(shl_ln103_12_fu_456_p2) - unsigned(shl_ln103_13_fu_462_p2));
    sub_ln103_7_fu_492_p2 <= std_logic_vector(unsigned(shl_ln103_14_fu_480_p2) - unsigned(shl_ln103_15_fu_486_p2));
    sub_ln103_8_fu_504_p2 <= std_logic_vector(unsigned(sub_ln103_7_fu_492_p2) - unsigned(shl_ln103_16_fu_498_p2));
    sub_ln103_9_fu_510_p1 <= in_11_val;
    sub_ln103_9_fu_510_p2 <= std_logic_vector(unsigned(sub_ln103_8_fu_504_p2) - unsigned(sub_ln103_9_fu_510_p1));
    sub_ln103_fu_342_p2 <= std_logic_vector(unsigned(shl_ln103_fu_330_p2) - unsigned(shl_ln103_1_fu_336_p2));
    sub_ln114_fu_1578_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_7) - unsigned(add_ln103_55_fu_1524_p2));
    sub_ln115_fu_1584_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_6) - unsigned(add_ln103_48_fu_1422_p2));
    sub_ln116_fu_1590_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_5) - unsigned(add_ln103_41_fu_1254_p2));
    sub_ln117_fu_1596_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_4) - unsigned(add_ln103_34_fu_1128_p2));
    sub_ln118_fu_1602_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_3) - unsigned(add_ln103_27_fu_972_p2));
    sub_ln119_fu_1608_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_2) - unsigned(add_ln103_20_fu_834_p2));
    sub_ln120_fu_1614_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_1) - unsigned(add_ln103_13_fu_684_p2));
    sub_ln121_fu_1620_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B8_fu_164_ap_return_0) - unsigned(add_ln103_6_fu_588_p2));
end behav;
