-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity IDCT2_IDCT2B2 is
port (
    ap_ready : OUT STD_LOGIC;
    in_0_val : IN STD_LOGIC_VECTOR (25 downto 0);
    in_1_val : IN STD_LOGIC_VECTOR (25 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of IDCT2_IDCT2B2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal add_ln19_fu_30_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal diff_fu_24_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal even_fu_36_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal odd_fu_44_p3 : STD_LOGIC_VECTOR (31 downto 0);


begin



    add_ln19_fu_30_p2 <= std_logic_vector(unsigned(in_1_val) + unsigned(in_0_val));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= even_fu_36_p3;
    ap_return_1 <= odd_fu_44_p3;
    diff_fu_24_p2 <= std_logic_vector(unsigned(in_0_val) - unsigned(in_1_val));
    even_fu_36_p3 <= (add_ln19_fu_30_p2 & ap_const_lv6_0);
    odd_fu_44_p3 <= (diff_fu_24_p2 & ap_const_lv6_0);
end behav;
