// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module IDCT2_IDCT2B2 (
        ap_ready,
        in_0_val,
        in_1_val,
        ap_return_0,
        ap_return_1,
        ap_rst
);


output   ap_ready;
input  [25:0] in_0_val;
input  [25:0] in_1_val;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
input   ap_rst;

wire   [25:0] add_ln19_fu_30_p2;
wire   [25:0] diff_fu_24_p2;
wire   [31:0] even_fu_36_p3;
wire   [31:0] odd_fu_44_p3;

assign add_ln19_fu_30_p2 = (in_1_val + in_0_val);

assign ap_ready = 1'b1;

assign diff_fu_24_p2 = (in_0_val - in_1_val);

assign even_fu_36_p3 = {{add_ln19_fu_30_p2}, {6'd0}};

assign odd_fu_44_p3 = {{diff_fu_24_p2}, {6'd0}};

assign ap_return_0 = even_fu_36_p3;

assign ap_return_1 = odd_fu_44_p3;

endmodule //IDCT2_IDCT2B2
