set SynModuleInfo {
  {SRCNAME IDCT2B2 MODELNAME IDCT2B2 RTLNAME IDCT2_IDCT2B2}
  {SRCNAME IDCT2B4 MODELNAME IDCT2B4 RTLNAME IDCT2_IDCT2B4
    SUBMODULES {
      {MODELNAME IDCT2_mul_32s_8s_32_1_1 RTLNAME IDCT2_mul_32s_8s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME IDCT2B8 MODELNAME IDCT2B8 RTLNAME IDCT2_IDCT2B8
    SUBMODULES {
      {MODELNAME IDCT2_mul_32s_7s_32_1_1 RTLNAME IDCT2_mul_32s_7s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME IDCT2B16 MODELNAME IDCT2B16 RTLNAME IDCT2_IDCT2B16
    SUBMODULES {
      {MODELNAME IDCT2_mul_32s_6s_32_1_1 RTLNAME IDCT2_mul_32s_6s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME IDCT2B32 MODELNAME IDCT2B32 RTLNAME IDCT2_IDCT2B32
    SUBMODULES {
      {MODELNAME IDCT2_mul_32s_5s_32_1_1 RTLNAME IDCT2_mul_32s_5s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME IDCT2B64 MODELNAME IDCT2B64 RTLNAME IDCT2_IDCT2B64
    SUBMODULES {
      {MODELNAME IDCT2_mul_32s_12s_32_1_1 RTLNAME IDCT2_mul_32s_12s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME IDCT2_mul_32s_9s_32_1_1 RTLNAME IDCT2_mul_32s_9s_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME IDCT2 MODELNAME IDCT2 RTLNAME IDCT2 IS_TOP 1
    SUBMODULES {
      {MODELNAME IDCT2_gmem0_m_axi RTLNAME IDCT2_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME IDCT2_gmem1_m_axi RTLNAME IDCT2_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME IDCT2_control_s_axi RTLNAME IDCT2_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME IDCT2_flow_control_loop_pipe RTLNAME IDCT2_flow_control_loop_pipe BINDTYPE interface TYPE internal_upc_flow_control INSTNAME IDCT2_flow_control_loop_pipe_U}
    }
  }
}
