-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity IDST7_IDST7B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idst7_32_2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of IDST7_IDST7B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idst7_32_2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010101", 1 => "00101010", 2 => "00111100", 3 => "01001010", 
    4 => "01010100", 5 => "01011001", 6 => "01011001", 7 => "01010100", 
    8 => "01001010", 9 => "00111100", 10 => "00101010", 11 => "00010101", 
    12 => "00000000", 13 => "11101011", 14 => "11010110", 15 => "11000100", 
    16 => "10110110", 17 => "10101100", 18 => "10100111", 19 => "10100111", 
    20 => "10101100", 21 => "10110110", 22 => "11000100", 23 => "11010110", 
    24 => "11101011", 25 => "00000000", 26 => "00010101", 27 => "00101010", 
    28 => "00111100", 29 => "01001010", 30 => "01010100", 31 => "01011001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

