-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity IDST7_IDST7B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idst7_32_9_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of IDST7_IDST7B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idst7_32_9_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "01001000", 1 => "01010110", 2 => "00100010", 3 => "11010010", 
    4 => "10100111", 5 => "11000001", 6 => "00001101", 7 => "01001110", 
    8 => "01010010", 9 => "00010101", 10 => "11001000", 11 => "10100110", 
    12 => "11001011", 13 => "00011010", 14 => "01010100", 15 => "01001101", 
    16 => "00001001", 17 => "10111110", 18 => "10101000", 19 => "11010110", 
    20 => "00100110", 21 => "01010111", 22 => "01000100", 23 => "11111100", 
    24 => "10110110", 25 => "10101011", 26 => "11100010", 27 => "00110010", 
    28 => "01011010", 29 => "00111100", 30 => "11101111", 31 => "10110000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

