-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity IDST7_IDST7B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idst7_32_0_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of IDST7_IDST7B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idst7_32_0_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000100", 1 => "0001001", 2 => "0001101", 3 => "0010001", 
    4 => "0010101", 5 => "0011010", 6 => "0011110", 7 => "0100010", 
    8 => "0100110", 9 => "0101010", 10 => "0101110", 11 => "0110010", 
    12 => "0110101", 13 => "0111000", 14 => "0111100", 15 => "0111111", 
    16 => "1000010", 17 => "1000100", 18 => "1001000", 19 => "1001010", 
    20 => "1001101", 21 => "1001110", 22 => "1010000", 23 => "1010010", 
    24 => "1010100", 25 => "1010101", 26 => "1010110", 27 => "1010111", 
    28 => "1011000", 29 => "1011001", 30 => "1011010", 31 => "1011010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

