-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity IDST7_IDST7B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idst7_32_1_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of IDST7_IDST7B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idst7_32_1_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001101", 1 => "00011010", 2 => "00100110", 3 => "00110010", 
    4 => "00111100", 5 => "01000100", 6 => "01001101", 7 => "01010010", 
    8 => "01010110", 9 => "01011001", 10 => "01011010", 11 => "01011000", 
    12 => "01010101", 13 => "01010000", 14 => "01001010", 15 => "01000010", 
    16 => "00111000", 17 => "00101110", 18 => "00100010", 19 => "00010101", 
    20 => "00001001", 21 => "11111100", 22 => "11101111", 23 => "11100010", 
    24 => "11010110", 25 => "11001011", 26 => "11000001", 27 => "10111000", 
    28 => "10110010", 29 => "10101100", 30 => "10101001", 31 => "10100110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

