-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity IDST7_IDST7B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idst7_32_30_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of IDST7_IDST7B32_Pipeline_VITIS_LOOP_73_1_p_ZL8idst7_32_30_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010001", 1 => "11011110", 2 => "00110010", 3 => "11000001", 
    4 => "01001010", 5 => "10101110", 6 => "01010111", 7 => "10100110", 
    8 => "01011000", 9 => "10101100", 10 => "01001101", 11 => "10111110", 
    12 => "00110101", 13 => "11011010", 14 => "00010101", 15 => "11111100", 
    16 => "11110011", 17 => "00011110", 18 => "11010010", 19 => "00111100", 
    20 => "10111000", 21 => "01010000", 22 => "10101010", 23 => "01011010", 
    24 => "10100111", 25 => "01010101", 26 => "10110010", 27 => "01000100", 
    28 => "11001000", 29 => "00101010", 30 => "11100110", 31 => "00001001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

