-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity IDCT2_IDCT2B8 is
port (
    ap_ready : OUT STD_LOGIC;
    in_0_val : IN STD_LOGIC_VECTOR (25 downto 0);
    in_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_4_val : IN STD_LOGIC_VECTOR (25 downto 0);
    in_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
    in_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of IDCT2_IDCT2B8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_FFFFFFA7 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111110100111";
    constant ap_const_lv32_FFFFFFCE : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111001110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal call_ret_IDCT2B4_fu_92_ap_ready : STD_LOGIC;
    signal call_ret_IDCT2B4_fu_92_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B4_fu_92_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B4_fu_92_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ret_IDCT2B4_fu_92_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln66_fu_104_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln66_1_fu_110_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln67_fu_116_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln68_fu_122_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln68_1_fu_128_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln65_fu_150_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_1_fu_156_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln65_fu_162_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_2_fu_168_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln65_1_fu_174_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_3_fu_186_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_4_fu_192_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_3_fu_186_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_4_fu_192_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_5_fu_204_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_4_fu_198_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_5_fu_204_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln65_2_fu_210_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln65_3_fu_216_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_6_fu_222_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_7_fu_228_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_6_fu_222_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_7_fu_228_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_8_fu_240_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln65_4_fu_234_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_8_fu_240_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_9_fu_252_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_10_fu_258_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_9_fu_252_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln65_10_fu_258_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_3_fu_180_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_5_fu_246_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln65_3_fu_216_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_6_fu_264_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_1_fu_276_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_fu_270_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln66_fu_288_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln66_1_fu_294_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln66_3_fu_300_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln66_2_fu_306_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln66_fu_312_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln66_3_fu_330_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln66_2_fu_324_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln66_3_fu_330_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln66_1_fu_318_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln66_fu_104_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln66_3_fu_336_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln66_1_fu_110_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln66_1_fu_348_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln66_fu_342_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln67_fu_360_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln67_fu_366_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln67_1_fu_384_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln67_1_fu_384_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln67_2_fu_396_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln67_5_fu_390_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln67_2_fu_396_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln67_1_fu_402_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln67_2_fu_408_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln67_3_fu_372_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln67_4_fu_378_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln67_fu_116_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln67_2_fu_408_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln67_1_fu_420_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln67_fu_414_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln68_fu_444_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln68_4_fu_438_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln68_fu_444_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln68_fu_450_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln68_1_fu_456_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln68_3_fu_432_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln68_1_fu_456_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln68_fu_122_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln68_1_fu_128_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln68_1_fu_468_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln68_fu_462_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_2_fu_282_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln66_2_fu_354_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln67_2_fu_426_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln68_2_fu_474_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln70_fu_480_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln71_fu_486_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln72_fu_492_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln73_fu_498_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln74_fu_504_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln75_fu_510_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln76_fu_516_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln77_fu_522_p2 : STD_LOGIC_VECTOR (31 downto 0);

    component IDCT2_IDCT2B4 IS
    port (
        ap_ready : OUT STD_LOGIC;
        in_0_val : IN STD_LOGIC_VECTOR (25 downto 0);
        in_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
        in_2_val : IN STD_LOGIC_VECTOR (25 downto 0);
        in_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;


    component IDCT2_mul_32s_8s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component IDCT2_mul_32s_7s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    call_ret_IDCT2B4_fu_92 : component IDCT2_IDCT2B4
    port map (
        ap_ready => call_ret_IDCT2B4_fu_92_ap_ready,
        in_0_val => in_0_val,
        in_1_val => in_2_val,
        in_2_val => in_4_val,
        in_3_val => in_6_val,
        ap_return_0 => call_ret_IDCT2B4_fu_92_ap_return_0,
        ap_return_1 => call_ret_IDCT2B4_fu_92_ap_return_1,
        ap_return_2 => call_ret_IDCT2B4_fu_92_ap_return_2,
        ap_return_3 => call_ret_IDCT2B4_fu_92_ap_return_3,
        ap_rst => ap_rst);

    mul_32s_8s_32_1_1_U9 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_5_val,
        din1 => mul_ln66_fu_104_p1,
        dout => mul_ln66_fu_104_p2);

    mul_32s_7s_32_1_1_U10 : component IDCT2_mul_32s_7s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 7,
        dout_WIDTH => 32)
    port map (
        din0 => in_7_val,
        din1 => mul_ln66_1_fu_110_p1,
        dout => mul_ln66_1_fu_110_p2);

    mul_32s_8s_32_1_1_U11 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_3_val,
        din1 => mul_ln67_fu_116_p1,
        dout => mul_ln67_fu_116_p2);

    mul_32s_7s_32_1_1_U12 : component IDCT2_mul_32s_7s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 7,
        dout_WIDTH => 32)
    port map (
        din0 => in_3_val,
        din1 => mul_ln68_fu_122_p1,
        dout => mul_ln68_fu_122_p2);

    mul_32s_8s_32_1_1_U13 : component IDCT2_mul_32s_8s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => in_7_val,
        din1 => mul_ln68_1_fu_128_p1,
        dout => mul_ln68_1_fu_128_p2);




    add_ln65_1_fu_276_p2 <= std_logic_vector(unsigned(sub_ln65_3_fu_216_p2) + unsigned(add_ln65_6_fu_264_p2));
    add_ln65_2_fu_282_p2 <= std_logic_vector(unsigned(add_ln65_1_fu_276_p2) + unsigned(add_ln65_fu_270_p2));
    add_ln65_3_fu_180_p2 <= std_logic_vector(unsigned(sub_ln65_1_fu_174_p2) + unsigned(in_1_val));
    add_ln65_4_fu_198_p2 <= std_logic_vector(unsigned(shl_ln65_3_fu_186_p2) + unsigned(shl_ln65_4_fu_192_p2));
    add_ln65_5_fu_246_p2 <= std_logic_vector(unsigned(sub_ln65_4_fu_234_p2) + unsigned(shl_ln65_8_fu_240_p2));
    add_ln65_6_fu_264_p2 <= std_logic_vector(unsigned(shl_ln65_9_fu_252_p2) + unsigned(shl_ln65_10_fu_258_p2));
    add_ln65_fu_270_p2 <= std_logic_vector(unsigned(add_ln65_3_fu_180_p2) + unsigned(add_ln65_5_fu_246_p2));
    add_ln66_1_fu_348_p2 <= std_logic_vector(unsigned(sub_ln66_3_fu_336_p2) + unsigned(mul_ln66_1_fu_110_p2));
    add_ln66_2_fu_354_p2 <= std_logic_vector(unsigned(add_ln66_1_fu_348_p2) + unsigned(add_ln66_fu_342_p2));
    add_ln66_3_fu_300_p2 <= std_logic_vector(unsigned(shl_ln66_fu_288_p2) + unsigned(shl_ln66_1_fu_294_p2));
    add_ln66_fu_342_p2 <= std_logic_vector(unsigned(sub_ln66_1_fu_318_p2) + unsigned(mul_ln66_fu_104_p2));
    add_ln67_1_fu_420_p2 <= std_logic_vector(unsigned(mul_ln67_fu_116_p2) + unsigned(sub_ln67_2_fu_408_p2));
    add_ln67_2_fu_426_p2 <= std_logic_vector(unsigned(add_ln67_1_fu_420_p2) + unsigned(add_ln67_fu_414_p2));
    add_ln67_3_fu_372_p2 <= std_logic_vector(unsigned(sub_ln67_fu_360_p2) + unsigned(shl_ln67_fu_366_p2));
    add_ln67_4_fu_378_p2 <= std_logic_vector(unsigned(shl_ln65_7_fu_228_p2) + unsigned(shl_ln65_8_fu_240_p2));
    add_ln67_5_fu_390_p2 <= std_logic_vector(unsigned(shl_ln67_1_fu_384_p2) + unsigned(shl_ln65_9_fu_252_p2));
    add_ln67_fu_414_p2 <= std_logic_vector(unsigned(add_ln67_3_fu_372_p2) + unsigned(add_ln67_4_fu_378_p2));
    add_ln68_1_fu_468_p2 <= std_logic_vector(unsigned(mul_ln68_fu_122_p2) + unsigned(mul_ln68_1_fu_128_p2));
    add_ln68_2_fu_474_p2 <= std_logic_vector(unsigned(add_ln68_1_fu_468_p2) + unsigned(add_ln68_fu_462_p2));
    add_ln68_3_fu_432_p2 <= std_logic_vector(unsigned(shl_ln66_1_fu_294_p2) + unsigned(shl_ln67_fu_366_p2));
    add_ln68_4_fu_438_p2 <= std_logic_vector(unsigned(shl_ln65_6_fu_222_p2) + unsigned(shl_ln65_7_fu_228_p2));
    add_ln68_fu_462_p2 <= std_logic_vector(unsigned(add_ln68_3_fu_432_p2) + unsigned(sub_ln68_1_fu_456_p2));
    add_ln70_fu_480_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B4_fu_92_ap_return_0) + unsigned(add_ln65_2_fu_282_p2));
    add_ln71_fu_486_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B4_fu_92_ap_return_1) + unsigned(add_ln66_2_fu_354_p2));
    add_ln72_fu_492_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B4_fu_92_ap_return_2) + unsigned(add_ln67_2_fu_426_p2));
    add_ln73_fu_498_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B4_fu_92_ap_return_3) + unsigned(add_ln68_2_fu_474_p2));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln70_fu_480_p2;
    ap_return_1 <= add_ln71_fu_486_p2;
    ap_return_2 <= add_ln72_fu_492_p2;
    ap_return_3 <= add_ln73_fu_498_p2;
    ap_return_4 <= sub_ln74_fu_504_p2;
    ap_return_5 <= sub_ln75_fu_510_p2;
    ap_return_6 <= sub_ln76_fu_516_p2;
    ap_return_7 <= sub_ln77_fu_522_p2;
    mul_ln66_1_fu_110_p1 <= ap_const_lv32_FFFFFFCE(7 - 1 downto 0);
    mul_ln66_fu_104_p1 <= ap_const_lv32_FFFFFFA7(8 - 1 downto 0);
    mul_ln67_fu_116_p1 <= ap_const_lv32_FFFFFFA7(8 - 1 downto 0);
    mul_ln68_1_fu_128_p1 <= ap_const_lv32_FFFFFFA7(8 - 1 downto 0);
    mul_ln68_fu_122_p1 <= ap_const_lv32_FFFFFFCE(7 - 1 downto 0);
    shl_ln65_10_fu_258_p0 <= in_7_val;
    shl_ln65_10_fu_258_p2 <= std_logic_vector(shift_left(unsigned(shl_ln65_10_fu_258_p0),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln65_1_fu_156_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_5(31-1 downto 0)))));
    shl_ln65_2_fu_168_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_3(31-1 downto 0)))));
    shl_ln65_3_fu_186_p0 <= in_3_val;
    shl_ln65_3_fu_186_p2 <= std_logic_vector(shift_left(unsigned(shl_ln65_3_fu_186_p0),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln65_4_fu_192_p0 <= in_3_val;
    shl_ln65_4_fu_192_p2 <= std_logic_vector(shift_left(unsigned(shl_ln65_4_fu_192_p0),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln65_5_fu_204_p0 <= in_3_val;
    shl_ln65_5_fu_204_p2 <= std_logic_vector(shift_left(unsigned(shl_ln65_5_fu_204_p0),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln65_6_fu_222_p0 <= in_5_val;
    shl_ln65_6_fu_222_p2 <= std_logic_vector(shift_left(unsigned(shl_ln65_6_fu_222_p0),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln65_7_fu_228_p0 <= in_5_val;
    shl_ln65_7_fu_228_p2 <= std_logic_vector(shift_left(unsigned(shl_ln65_7_fu_228_p0),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln65_8_fu_240_p0 <= in_5_val;
    shl_ln65_8_fu_240_p2 <= std_logic_vector(shift_left(unsigned(shl_ln65_8_fu_240_p0),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln65_9_fu_252_p0 <= in_7_val;
    shl_ln65_9_fu_252_p2 <= std_logic_vector(shift_left(unsigned(shl_ln65_9_fu_252_p0),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln65_fu_150_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_7(31-1 downto 0)))));
    shl_ln66_1_fu_294_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    shl_ln66_2_fu_306_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln66_3_fu_330_p0 <= in_3_val;
    shl_ln66_3_fu_330_p2 <= std_logic_vector(shift_left(unsigned(shl_ln66_3_fu_330_p0),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln66_fu_288_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln67_1_fu_384_p0 <= in_7_val;
    shl_ln67_1_fu_384_p2 <= std_logic_vector(shift_left(unsigned(shl_ln67_1_fu_384_p0),to_integer(unsigned('0' & ap_const_lv32_6(31-1 downto 0)))));
    shl_ln67_2_fu_396_p0 <= in_7_val;
    shl_ln67_2_fu_396_p2 <= std_logic_vector(shift_left(unsigned(shl_ln67_2_fu_396_p0),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    shl_ln67_fu_366_p2 <= std_logic_vector(shift_left(unsigned(in_1_val),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    shl_ln68_fu_444_p0 <= in_5_val;
    shl_ln68_fu_444_p2 <= std_logic_vector(shift_left(unsigned(shl_ln68_fu_444_p0),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    sub_ln65_1_fu_174_p2 <= std_logic_vector(unsigned(sub_ln65_fu_162_p2) - unsigned(shl_ln65_2_fu_168_p2));
    sub_ln65_2_fu_210_p2 <= std_logic_vector(unsigned(add_ln65_4_fu_198_p2) - unsigned(shl_ln65_5_fu_204_p2));
    sub_ln65_3_fu_216_p1 <= in_3_val;
    sub_ln65_3_fu_216_p2 <= std_logic_vector(unsigned(sub_ln65_2_fu_210_p2) - unsigned(sub_ln65_3_fu_216_p1));
    sub_ln65_4_fu_234_p2 <= std_logic_vector(unsigned(shl_ln65_6_fu_222_p2) - unsigned(shl_ln65_7_fu_228_p2));
    sub_ln65_fu_162_p2 <= std_logic_vector(unsigned(shl_ln65_fu_150_p2) - unsigned(shl_ln65_1_fu_156_p2));
    sub_ln66_1_fu_318_p2 <= std_logic_vector(unsigned(sub_ln66_fu_312_p2) - unsigned(in_1_val));
    sub_ln66_2_fu_324_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(shl_ln65_4_fu_192_p2));
    sub_ln66_3_fu_336_p2 <= std_logic_vector(unsigned(sub_ln66_2_fu_324_p2) - unsigned(shl_ln66_3_fu_330_p2));
    sub_ln66_fu_312_p2 <= std_logic_vector(unsigned(add_ln66_3_fu_300_p2) - unsigned(shl_ln66_2_fu_306_p2));
    sub_ln67_1_fu_402_p2 <= std_logic_vector(unsigned(add_ln67_5_fu_390_p2) - unsigned(shl_ln67_2_fu_396_p2));
    sub_ln67_2_fu_408_p1 <= in_7_val;
    sub_ln67_2_fu_408_p2 <= std_logic_vector(unsigned(sub_ln67_1_fu_402_p2) - unsigned(sub_ln67_2_fu_408_p1));
    sub_ln67_fu_360_p2 <= std_logic_vector(unsigned(shl_ln66_fu_288_p2) - unsigned(shl_ln66_1_fu_294_p2));
    sub_ln68_1_fu_456_p1 <= in_5_val;
    sub_ln68_1_fu_456_p2 <= std_logic_vector(unsigned(sub_ln68_fu_450_p2) - unsigned(sub_ln68_1_fu_456_p1));
    sub_ln68_fu_450_p2 <= std_logic_vector(unsigned(add_ln68_4_fu_438_p2) - unsigned(shl_ln68_fu_444_p2));
    sub_ln74_fu_504_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B4_fu_92_ap_return_3) - unsigned(add_ln68_2_fu_474_p2));
    sub_ln75_fu_510_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B4_fu_92_ap_return_2) - unsigned(add_ln67_2_fu_426_p2));
    sub_ln76_fu_516_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B4_fu_92_ap_return_1) - unsigned(add_ln66_2_fu_354_p2));
    sub_ln77_fu_522_p2 <= std_logic_vector(unsigned(call_ret_IDCT2B4_fu_92_ap_return_0) - unsigned(add_ln65_2_fu_282_p2));
end behav;
