// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module IDST7_IDST7B16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src_0_val,
        src_1_val,
        src_2_val,
        src_3_val,
        src_4_val,
        src_5_val,
        src_6_val,
        src_7_val,
        src_8_val,
        src_9_val,
        src_10_val,
        src_11_val,
        src_12_val,
        src_13_val,
        src_14_val,
        src_15_val,
        dst_0,
        dst_0_ap_vld,
        dst_1,
        dst_1_ap_vld,
        dst_2,
        dst_2_ap_vld,
        dst_3,
        dst_3_ap_vld,
        dst_4,
        dst_4_ap_vld,
        dst_5,
        dst_5_ap_vld,
        dst_6,
        dst_6_ap_vld,
        dst_7,
        dst_7_ap_vld,
        dst_8,
        dst_8_ap_vld,
        dst_9,
        dst_9_ap_vld,
        dst_10,
        dst_10_ap_vld,
        dst_11,
        dst_11_ap_vld,
        dst_12,
        dst_12_ap_vld,
        dst_13,
        dst_13_ap_vld,
        dst_14,
        dst_14_ap_vld,
        dst_15,
        dst_15_ap_vld,
        shift,
        skipLine2,
        oMin,
        oMax
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] src_0_val;
input  [31:0] src_1_val;
input  [31:0] src_2_val;
input  [31:0] src_3_val;
input  [31:0] src_4_val;
input  [31:0] src_5_val;
input  [31:0] src_6_val;
input  [31:0] src_7_val;
input  [31:0] src_8_val;
input  [31:0] src_9_val;
input  [31:0] src_10_val;
input  [31:0] src_11_val;
input  [31:0] src_12_val;
input  [31:0] src_13_val;
input  [31:0] src_14_val;
input  [31:0] src_15_val;
output  [31:0] dst_0;
output   dst_0_ap_vld;
output  [31:0] dst_1;
output   dst_1_ap_vld;
output  [31:0] dst_2;
output   dst_2_ap_vld;
output  [31:0] dst_3;
output   dst_3_ap_vld;
output  [31:0] dst_4;
output   dst_4_ap_vld;
output  [31:0] dst_5;
output   dst_5_ap_vld;
output  [31:0] dst_6;
output   dst_6_ap_vld;
output  [31:0] dst_7;
output   dst_7_ap_vld;
output  [31:0] dst_8;
output   dst_8_ap_vld;
output  [31:0] dst_9;
output   dst_9_ap_vld;
output  [31:0] dst_10;
output   dst_10_ap_vld;
output  [31:0] dst_11;
output   dst_11_ap_vld;
output  [31:0] dst_12;
output   dst_12_ap_vld;
output  [31:0] dst_13;
output   dst_13_ap_vld;
output  [31:0] dst_14;
output   dst_14_ap_vld;
output  [31:0] dst_15;
output   dst_15_ap_vld;
input  [31:0] shift;
input  [31:0] skipLine2;
input  [31:0] oMin;
input  [31:0] oMax;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] dst_0;
reg[31:0] dst_1;
reg[31:0] dst_2;
reg[31:0] dst_3;
reg[31:0] dst_4;
reg[31:0] dst_5;
reg[31:0] dst_6;
reg[31:0] dst_7;
reg[31:0] dst_8;
reg[31:0] dst_9;
reg[31:0] dst_10;
reg[31:0] dst_11;
reg[31:0] dst_12;
reg[31:0] dst_13;
reg[31:0] dst_14;
reg[31:0] dst_15;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] tmp_reg_488;
wire   [31:0] trunc_ln43_fu_389_p1;
reg   [31:0] trunc_ln43_reg_493;
wire   [31:0] sub_ln43_fu_393_p2;
reg   [31:0] sub_ln43_reg_498;
reg   [0:0] tmp_23_reg_503;
wire    ap_CS_fsm_state2;
wire   [31:0] rndFactor_6_fu_417_p3;
reg   [31:0] rndFactor_6_reg_598;
wire   [31:0] cutoff_fu_425_p2;
reg   [31:0] cutoff_reg_603;
wire   [31:0] sub_i_i_i_i_fu_432_p2;
reg   [31:0] sub_i_i_i_i_reg_608;
reg   [30:0] tmp_24_reg_613;
reg   [29:0] tmp_25_reg_618;
reg   [28:0] tmp_26_reg_623;
reg   [27:0] tmp_27_reg_628;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_idle;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_ready;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld;
wire   [31:0] grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1;
wire    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld;
reg    grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg;
reg   [31:0] dst_0_reg;
wire    ap_CS_fsm_state3;
reg   [31:0] dst_15_reg;
reg   [31:0] dst_14_reg;
reg   [31:0] dst_13_reg;
reg   [31:0] dst_12_reg;
reg   [31:0] dst_11_reg;
reg   [31:0] dst_10_reg;
reg   [31:0] dst_9_reg;
reg   [31:0] dst_8_reg;
reg   [31:0] dst_7_reg;
reg   [31:0] dst_6_reg;
reg   [31:0] dst_5_reg;
reg   [31:0] dst_4_reg;
reg   [31:0] dst_3_reg;
reg   [31:0] dst_2_reg;
reg   [31:0] dst_1_reg;
wire  signed [31:0] sext_ln43_fu_371_p0;
wire  signed [32:0] sext_ln43_fu_371_p1;
wire   [32:0] add_ln43_fu_375_p2;
wire  signed [31:0] tmp_23_fu_399_p1;
wire   [31:0] rndFactor_fu_407_p2;
wire   [31:0] rndFactor_5_fu_412_p2;
wire  signed [31:0] sub_i_i_i_i_fu_432_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg = 1'b0;
end

IDST7_IDST7B16_Pipeline_VITIS_LOOP_47_1 grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start),
    .ap_done(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done),
    .ap_idle(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_idle),
    .ap_ready(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_ready),
    .dst_0(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0),
    .dst_0_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld),
    .dst_15(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15),
    .dst_15_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld),
    .dst_14(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14),
    .dst_14_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld),
    .dst_13(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13),
    .dst_13_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld),
    .dst_12(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12),
    .dst_12_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld),
    .dst_11(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11),
    .dst_11_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld),
    .dst_10(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10),
    .dst_10_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld),
    .dst_9(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9),
    .dst_9_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld),
    .dst_8(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8),
    .dst_8_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld),
    .dst_7(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7),
    .dst_7_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld),
    .dst_6(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6),
    .dst_6_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld),
    .dst_5(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5),
    .dst_5_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld),
    .dst_4(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4),
    .dst_4_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld),
    .dst_3(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3),
    .dst_3_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld),
    .dst_2(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2),
    .dst_2_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld),
    .dst_1(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1),
    .dst_1_ap_vld(grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld),
    .src_0_val(src_0_val),
    .src_1_val(src_1_val),
    .src_2_val(src_2_val),
    .src_3_val(src_3_val),
    .src_4_val(src_4_val),
    .src_5_val(src_5_val),
    .src_6_val(src_6_val),
    .src_7_val(src_7_val),
    .src_8_val(src_8_val),
    .src_9_val(src_9_val),
    .src_10_val(src_10_val),
    .src_11_val(src_11_val),
    .src_12_val(src_12_val),
    .src_13_val(src_13_val),
    .src_14_val(src_14_val),
    .src_15_val(src_15_val),
    .conv3_i12_i_i(rndFactor_6_reg_598),
    .sh_prom_i9_i_i(sub_i_i_i_i_reg_608),
    .sh_prom_i_i_i(shift),
    .empty_41(tmp_23_reg_503),
    .oMin(oMin),
    .oMax(oMax),
    .empty_42(tmp_27_reg_628),
    .cutoff(cutoff_reg_603),
    .empty_43(tmp_26_reg_623),
    .empty_44(tmp_25_reg_618),
    .empty(tmp_24_reg_613)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg <= 1'b1;
        end else if ((grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_ready == 1'b1)) begin
            grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cutoff_reg_603 <= cutoff_fu_425_p2;
        rndFactor_6_reg_598 <= rndFactor_6_fu_417_p3;
        sub_i_i_i_i_reg_608 <= sub_i_i_i_i_fu_432_p2;
        tmp_24_reg_613 <= {{cutoff_fu_425_p2[31:1]}};
        tmp_25_reg_618 <= {{cutoff_fu_425_p2[31:2]}};
        tmp_26_reg_623 <= {{cutoff_fu_425_p2[31:3]}};
        tmp_27_reg_628 <= {{cutoff_fu_425_p2[31:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld == 1'b1))) begin
        dst_0_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld == 1'b1))) begin
        dst_10_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld == 1'b1))) begin
        dst_11_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld == 1'b1))) begin
        dst_12_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld == 1'b1))) begin
        dst_13_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld == 1'b1))) begin
        dst_14_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld == 1'b1))) begin
        dst_15_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld == 1'b1))) begin
        dst_1_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld == 1'b1))) begin
        dst_2_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld == 1'b1))) begin
        dst_3_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld == 1'b1))) begin
        dst_4_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld == 1'b1))) begin
        dst_5_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld == 1'b1))) begin
        dst_6_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld == 1'b1))) begin
        dst_7_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld == 1'b1))) begin
        dst_8_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld == 1'b1))) begin
        dst_9_reg <= grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sub_ln43_reg_498 <= sub_ln43_fu_393_p2;
        tmp_23_reg_503 <= tmp_23_fu_399_p1[32'd31];
        tmp_reg_488 <= add_ln43_fu_375_p2[32'd32];
        trunc_ln43_reg_493 <= trunc_ln43_fu_389_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done == 1'b1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld == 1'b1))) begin
        dst_0 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0;
    end else begin
        dst_0 = dst_0_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld == 1'b1))) begin
        dst_1 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1;
    end else begin
        dst_1 = dst_1_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld == 1'b1))) begin
        dst_10 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10;
    end else begin
        dst_10 = dst_10_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld == 1'b1))) begin
        dst_11 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11;
    end else begin
        dst_11 = dst_11_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld == 1'b1))) begin
        dst_12 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12;
    end else begin
        dst_12 = dst_12_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld == 1'b1))) begin
        dst_13 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13;
    end else begin
        dst_13 = dst_13_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld == 1'b1))) begin
        dst_14 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14;
    end else begin
        dst_14 = dst_14_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld == 1'b1))) begin
        dst_15 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15;
    end else begin
        dst_15 = dst_15_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld == 1'b1))) begin
        dst_2 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2;
    end else begin
        dst_2 = dst_2_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld == 1'b1))) begin
        dst_3 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3;
    end else begin
        dst_3 = dst_3_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld == 1'b1))) begin
        dst_4 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4;
    end else begin
        dst_4 = dst_4_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld == 1'b1))) begin
        dst_5 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5;
    end else begin
        dst_5 = dst_5_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld == 1'b1))) begin
        dst_6 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6;
    end else begin
        dst_6 = dst_6_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld == 1'b1))) begin
        dst_7 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7;
    end else begin
        dst_7 = dst_7_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld == 1'b1))) begin
        dst_8 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8;
    end else begin
        dst_8 = dst_8_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld == 1'b1))) begin
        dst_9 = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9;
    end else begin
        dst_9 = dst_9_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln43_fu_375_p2 = ($signed(sext_ln43_fu_371_p1) + $signed(33'd8589934591));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign cutoff_fu_425_p2 = (32'd16 - skipLine2);

assign dst_0_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_0_ap_vld;

assign dst_10_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_10_ap_vld;

assign dst_11_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_11_ap_vld;

assign dst_12_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_12_ap_vld;

assign dst_13_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_13_ap_vld;

assign dst_14_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_14_ap_vld;

assign dst_15_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_15_ap_vld;

assign dst_1_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_1_ap_vld;

assign dst_2_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_2_ap_vld;

assign dst_3_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_3_ap_vld;

assign dst_4_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_4_ap_vld;

assign dst_5_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_5_ap_vld;

assign dst_6_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_6_ap_vld;

assign dst_7_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_7_ap_vld;

assign dst_8_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_8_ap_vld;

assign dst_9_ap_vld = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_dst_9_ap_vld;

assign grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start = grp_IDST7B16_Pipeline_VITIS_LOOP_47_1_fu_258_ap_start_reg;

assign rndFactor_5_fu_412_p2 = 32'd1 << trunc_ln43_reg_493;

assign rndFactor_6_fu_417_p3 = ((tmp_reg_488[0:0] == 1'b1) ? rndFactor_fu_407_p2 : rndFactor_5_fu_412_p2);

assign rndFactor_fu_407_p2 = 32'd1 >> sub_ln43_reg_498;

assign sext_ln43_fu_371_p0 = shift;

assign sext_ln43_fu_371_p1 = sext_ln43_fu_371_p0;

assign sub_i_i_i_i_fu_432_p1 = shift;

assign sub_i_i_i_i_fu_432_p2 = ($signed(32'd0) - $signed(sub_i_i_i_i_fu_432_p1));

assign sub_ln43_fu_393_p2 = (32'd0 - trunc_ln43_fu_389_p1);

assign tmp_23_fu_399_p1 = shift;

assign trunc_ln43_fu_389_p1 = add_ln43_fu_375_p2[31:0];

endmodule //IDST7_IDST7B16
